<?php
$lang = array(
    'home' => 'Home',
    'about' => 'About Us',
    'contact' => 'Contact',
    'website_name' => 'COLAB Enriching All Our Institutions',
    'somosredet' => '#somosREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Community of Practice',
    'members' => 'Membership',
    'news' => 'News',
    'membresias' => 'Memberships',
    'saber_mas' => 'Learn More',
    'ser_miembro' => 'Become a Member',
    'ser_miembro_desc1' => 'All individual and institutional members of AETH interested in Hispanic/Latino theological education can be members of ReDET. They have the following categories of membership:',
    'ser_miembro_desc2' => '<b>Individual Membership:</b> For women and men serving as educators in theological education; students enrolled in any undergraduate theological institution, Bible institute, or ministerial training program; pastors or leaders of denominations and churches, or workers from religious or non-governmental organizations, and others interested in theological education.',
    'ser_miembro_desc3' => '<b>Organizational Membership:</b> For seminaries, faculties of theology, Bible institutes, service companies, or faith-based organizations.',
    'redet_name' => 'Network of Theological Entities (ReDET)',
    'redet_desc1' => 'Expanding connections through theological education.',
    'redt_desc2' => '<b>ReDET</b> is a community of people and entities created for mutual support, collaboration, and solving common problems in theological education.',
    'association' => 'Association for Hispanic Theological Education.',
    'description' => 'REDET is a network dedicated to advancing theological education throughout Latin America. It provides resources, collaborative opportunities, and training to support institutions in their mission to develop Christian leaders. By fostering partnerships among theological schools and promoting quality education, REDET aims to empower communities, enhance leadership development, and strengthen the impact of Christian ministry in the region.',
);
