<?php // lang_es.php
$lang = array(
    'title' => 'Bienvenido',
    'description' => 'L.O.V.E.',
    'home' => 'Inicio',
    'about' => 'Sobre Nosotros',
    'pages' => 'Páginas',
    'causes' => 'Causas',
    'blog' => 'Blog',
    'contact' => 'Contacto',
    'collection' => 'Colección',
    'friends' => 'Amigos del Centro',
    'subscription' => 'Suscripción',
    'website_name' => 'Centro de Recursos Justo & Catherine González',
    'about_the' => 'Sobre el Centro González',
    'mission' => 'Nuestra Misión',
    'mission_statement' => 'Promover y apoyar la contribución latina a la formación de líderes ministeriales a través del diálogo, recursos educativos e investigación.',
    'more_about' => 'Más Sobre Nosotros',
    'support_hispanic' => 'Apoyar a la Comunidad Hispana',
    'goal' => 'Nuestra Meta',
    'goal_1' => 'Un lugar de encuentro tanto físico como virtual que:',
    'goal_2' => 'Aumenta la conciencia sobre las perspectivas latinas y la herencia latina al proporcionar acceso digital a sus recursos;',
    'goal_3' => 'Explora nuevas fronteras en la teología latina y proporciona un foro para personas comprometidas con el bienestar de las iglesias y comunidades latinas para explorar y desarrollar nuevas visiones y prácticas.',
    'vision' => 'Nuestra Visión',
    'vision1' => 'Un lugar de encuentro tanto físico como virtual que:',
    'vision2' => 'Aumenta la conciencia sobre las perspectivas latinas y la herencia latina al proporcionar acceso digital a sus recursos;',
    'vision3' => 'Explora nuevas fronteras en la teología latina y proporciona un foro para personas comprometidas con el bienestar de las iglesias y comunidades latinas para explorar y desarrollar nuevas visiones y prácticas.',
    'testimonial1' => 'Los escritos de Justo y Catherine González han ayudado a los cristianos de todo el mundo a comprender la historia de la iglesia de maneras nuevas y más profundas. El Centro de Recursos realiza un trabajo esencial al hacer estos materiales disponibles para todas las personas.',
    'testimonial2' => 'La obra de vida de Justo González es un tesoro, y estoy emocionado de saber que se hará tan ampliamente disponible para la posteridad a través del Centro de Recursos Justo y Catherine González.',
    'testimonial3' => 'La amplitud de su trabajo en historia, teología y formación ministerial hace que el Centro de Recursos González sea un sitio indispensable de investigación de archivos y conversación dinámica sobre muchas de las preguntas teológicas más urgentes de nuestro tiempo.',
    'testimonial4' => 'Al abrazar su legado, fomentamos un paisaje teológico más inclusivo, ecuménico y vibrante, donde se construyen puentes entre la academia, los seminarios y la comunidad de la Iglesia en general.',
    'testimonial5' => 'Cuando miro hacia atrás en el último siglo de educación teológica y liderazgo pastoral en los Estados Unidos y en todo el mundo, no puedo pensar en dos personas tan influyentes como Justo y Catherine González.',
    'testimonial6' => 'Através do Centro Justo e Catherine Gonzalez, eles continuarão a inspirar, desafiar e encorajar as futuras gerações a abraçar, apreciar e celebrar o contínuo trabalho da graça abundante de Deus.',
    'email_address' => 'Dirección de Correo Electrónico',
    'our_location' => 'Nuestra Ubicación',
    'fell_free' => 'No dude en contactarnos',
    'justo_influence' => '<p>Justo Luis González nació en La Habana, Cuba, en agosto del 1937. Durante sus años mozos, sus padres echaron los cimientos para una carrera que le ha ocupado por más de 60 años.</p><p>Su madre, Luisa García Acosta, era educadora, profesora de literatura española, y autora de numerosos libros sobre gramática. Su padre, Justo González Carrasco, era novelista, editor de un diario, y empleado del Ministerio de Agricultura de Cuba, donde se ocupaba principalmente de tomar los materiales escritos por científicos acerca de temas tales como la agricultura, la higiene y las plantas medicinales, y escribirlos de tal modo que quienes no tuvieran una amplia educación formal pudieran entender y aplicar lo que leían.</p><p>Justo padre decía frecuentemente que quien no podía explicar algo en términos sencillos probablemente no lo entendía.</p><p>Justo aprendió esa lección directamente de su padre, cuando le presentó orgullosamente un ensayo que había sido altamente elogiado por su maestra. Tras leerlo repetidamente, su padre le preguntó: “¿Qué quisiste decir?” Cuando Justo se lo explicó, la respuesta de su padre fue: “Entonces. ¿Por qué no lo dijiste?”</p><p>Esa lección se ve todavía en todo lo que Justo escribe, frecuentemente tomando conceptos difíciles y explicándolos de tal manera que cualquier persona que se interese pueda entenderlos, sin importar cuánta educación formal haya tenido. Esto se ve claramente en sus más de 150 libros, entre los que se incluyen Historia del Cristianismo e Historia del Pensamiento Cristiano, traducidos a diez idiomas.</p><p>Tras completar sus estudios teológicos en el Seminario Evangélico de Teología en Matanzas, Cuba en el 1957, ser ordenado ministro metodista ese mismo año, y terminar su PhD en teología histórica en la Universidad de Yale –a los 23 años de edad– fue a Puerto Rico, donde enseñó historia de la iglesia en el Seminario Evangélico de Puerto Rico por espacio de ocho años. De allí pasó a enseñar en la escuela de teología Candler, en la universidad de Emory.</p><p>Durante más de 45 años, Justo ha enfocado su atención en el desarrollo de programas para la educación teológica del pueblo hispano. Esto ha resultado, entre otras cosas, en el Programa Hispano de Verano (HSP), la Asociación para la Educación Teológica Hispana (AETH) y la Iniciativa Teológica Hispana (HTI). La importancia de su obra ha sido reconocida mediante numerosos premios y distinciones, entre las que se incluyen siete doctorados honoris causa, el “Lifetime Achievement Award” de la Asociación de Escuelas Teológicas (ATS) y, sobre todo, un público lector de alcance global.</p><p>Tras su “jubilación”, Justo continúa escribiendo, dando conferencias, e inspirando a nuevas generaciones de líderes para la iglesia, particularmente entre el pueblo hispano.</p><p>Está casado con la Rvda. Dra. Catherine Gunsalus González, con quien colabora tanto en conferencias como en escritos conjuntos. Tienen una hija, dos nietas y tres bisnietos.</p>',
    'justo_legacy' => 'Legado de González',
    'justo_legacy_1' => 'El Dr. Justo L. González es un teólogo, historiador y educador distinguido, conocido particularmente por sus contribuciones a la teología hispana. Nacido y criado en La Habana, Cuba, González fue ordenado ministro en la iglesia metodista en 1957. Posteriormente, obtuvo su Ph.D. en Teología Histórica de la Universidad de Yale en 1961, convirtiéndose en la persona más joven en hacerlo en ese momento.',
    'justo_legacy_2' => 'A lo largo de su carrera, González ha enseñado en diversas instituciones teológicas, incluyendo el Seminario Evangélico de Puerto Rico y la Candler School of Theology de la Universidad de Emory. Ha escrito más de 150 libros, con obras notables como "Una Historia del Pensamiento Cristiano" y "La Historia del Cristianismo", que han sido traducidas a varios idiomas.',
    'justo_legacy_3' => 'El Dr. González ha sido fundamental en la promoción de la educación teológica hispana. Ayudó a fundar la Iniciativa Teológica Hispana, el Programa de Verano Hispano y la Asociación para la Educación Teológica Hispana (AETH). Su compromiso con la educación se refleja aún más en el Centro de Recursos Justo y Catherine González, establecido en 2011 para apoyar los ministerios latinos.',
    'justo_legacy_4' => 'Incluso después de retirarse de la enseñanza a tiempo completo, González continúa escribiendo, dando conferencias y mentoreando a jóvenes teólogos. Ha recibido numerosos reconocimientos, incluyendo cuatro doctorados honorarios y la Medalla al Servicio Distinguido de la Asociación de Escuelas Teológicas.',
    'justo_legacy_5' => 'El trabajo de González ha moldeado significativamente la hermenéutica bíblica latina/o y la teología constructiva, abogando por el reconocimiento de la naturaleza contextual de la teología y su enriquecimiento a través de diversas perspectivas culturales.',
    'degrees' => array(
        'bachelor_of_arts' => '<strong>Bachillerato en Artes (B.A.):</strong> Obtuvo su título de pregrado en teología en la Universidad de La Habana en Cuba.',
        'bachelor_of_divinity' => '<strong>Bachillerato en Divinidad (B.D.):</strong> González obtuvo su B.D. en el Union Theological Seminary en Nueva York.',
        'phd_historical_theology' => '<strong>Ph.D. en Teología Histórica:</strong> Obtuvo su Ph.D. en la Universidad de Yale en 1970, convirtiéndose en la persona más joven en hacerlo en ese momento.',
        'doctor_of_ministry' => '<strong>Doctorado en Ministerio (D.Min.):</strong> También posee un Doctorado en Ministerio, que enfatiza la aplicación práctica de la teología en contextos ministeriales.',
        'honorary_doctorates' => '<strong>Doctorados Honorarios:</strong> El Dr. González ha recibido múltiples doctorados honorarios de diversas instituciones en reconocimiento a sus contribuciones a la teología y la educación, aunque las instituciones específicas y los grados varían.',
    ),
    'achievements' => array(
        'first_latino_phd' => '<strong>Primer Latino en Obtener un Ph.D. de la Universidad de Yale:</strong> El Dr. González se convirtió en la persona más joven y el primer latino en graduarse con un Ph.D. en Teología Histórica de Yale en 1970.',
        'ordained_minister' => '<strong>Ministro Ordenado:</strong> Fue ordenado ministro en la Iglesia Metodista en 1957, comenzando su largo compromiso con el ministerio y la educación teológica.',
        'prolific_author' => '<strong>Autor Prolífico:</strong> El Dr. González ha escrito más de 150 libros sobre teología, historia y ministerio, contribuyendo significativamente a los campos de la teología hispana y latina/o.',
        'advocate_hispanic_education' => '<strong>Defensor de la Educación Teológica Hispana:</strong> Ha sido fundamental en la promoción y el desarrollo de la educación teológica para las comunidades hispanas, ayudando a establecer programas que atienden sus contextos culturales únicos.',
        'educator_renowned_institutions' => '<strong>Educador en Instituciones Reconocidas:</strong> El Dr. González ha enseñado en diversas instituciones teológicas prestigiosas, incluyendo la Candler School of Theology en la Universidad de Emory y el Centro Teológico Interdenominacional en Atlanta.',
        'international_speaker' => '<strong>Orador y Conferencista Internacional:</strong> El Dr. González ha dado conferencias en todo el mundo, compartiendo sus conocimientos sobre teología hispana, historia de la iglesia y la intersección entre la fe y la cultura.',
        'member_american_academy' => '<strong>Miembro de la Academia Americana de Artes y Ciencias:</strong> Sus contribuciones académicas le han valido un lugar en esta prestigiosa organización, reconociendo su influencia en las humanidades.',
        'founder_hispanic_initiative' => '<strong>Fundador de la Iniciativa Teológica Hispana:</strong> Co-fundó esta iniciativa para mejorar la capacitación y el apoyo a los académicos hispanos en la educación teológica.',
    ),
    'video' => 'González Videos',
    'gallery' => 'Galeria',
    'Advanced_Search' => 'Búsqueda Avanzada',
    'Faceted_Search' => 'Búsqueda Facetada',
    'User_Friendly_Interface' => 'Interfaz Amigable para el Usuario',
    'Rich_Metadata_Integration' => 'Integración de Metadatos Ricos',
    'discovery' => 'Descubre el Magnífico Acervo',
    'discovery_description1' => 'Nuestra plataforma presenta con orgullo el magnífico contenido del acervo de Justo y Catherine Gonzalez, ofreciendo una riqueza inigualable de información y recursos para una investigación y exploración en profundidad. Esta colección exclusiva es un tesoro de valiosos conocimientos y datos históricos, meticulosamente curada para el investigador exigente.',
    'discovery2' => 'Desbloquea Acceso Premium',
    'discovery_description2' => 'Para mantener los más altos estándares de privacidad e integridad, el acceso a este contenido extraordinario está disponible a través de un inicio de sesión seguro. No pierdas la oportunidad de sumergirte en esta colección excepcional—contáctanos para obtener tus credenciales de acceso y explorar la riqueza de nuestro acervo.',
    'youtube_title' => 'Bienvenido al Canal de Videos de González',
    'youtube_description' => 'Sumérgete en el exclusivo mundo de Justo y Catherine Gonzalez con nuestro canal de YouTube, tu puerta de entrada a una rica colección de contenido curado. Nuestro canal ofrece una variedad de videos únicos e insights que no están disponibles en ningún otro lugar.',
    'Exclusive_Content' => 'Contenido Exclusivo',
    'youtube_description2' => 'Disfruta de acceso a una variedad de videos exclusivos que incluyen exploraciones detalladas, entrevistas y contenido detrás de cámaras relacionado con Justo y Catherine Gonzalez. Descubre material raro y exclusivo que proporciona una comprensión más profunda de su trabajo y legado.',
    'friend_of_the_center_title' => 'Conviértete en Amigo del Centro',
    'friend_of_the_center_description' => 'Únete a nosotros para mantener el valioso trabajo del Centro de Recursos Justo Gonzalez convirtiéndote en un “Amigo del Centro.” Tu apoyo es crucial para mantener y mejorar los recursos y programas de nuestro centro.',
    'why_become' => '¿Por qué Convertirse en Amigo del Centro?',
    'sustain_services' => '<strong>Sostén Servicios Esenciales:</strong> Tu donación mensual o anual ayuda a garantizar que nuestro centro continúe ofreciendo servicios y recursos esenciales a quienes los necesitan.',
    'preserve_resources' => '<strong>Preserva Recursos Valiosos:</strong> Las contribuciones nos ayudan a mantener y ampliar nuestra colección, permitiéndonos ofrecer más materiales valiosos y oportunidades para la investigación y la educación.',
    'make_impact' => '<strong>Haz un Impacto Duradero:</strong> Al unirte al programa “Amigo del Centro,” estás desempeñando un papel vital en la preservación y promoción del legado de Justo Gonzalez, asegurando que las futuras generaciones puedan seguir accediendo y aprendiendo de este recurso invaluable.',
    'benefits' => 'Beneficios de Unirse',
    'exclusive_updates' => 'Actualizaciones Exclusivas: Recibe actualizaciones regulares sobre las actividades del centro, nuevas adquisiciones y eventos especiales.',
    'recognition' => 'Reconocimiento: Como muestra de nuestro agradecimiento, serás reconocido por tu generoso apoyo en nuestras publicaciones y en nuestro sitio web.',
    'special_access' => 'Acceso Especial: Disfruta de acceso exclusivo a eventos especiales y vistas previas de nuevos recursos y colecciones.',
    'how_to_get_involved' => 'Cómo Participar',
    'simple_process' => 'Convertirse en un “Amigo del Centro” es simple. Elige un plan de donación mensual o anual que se ajuste a tu presupuesto y marca la diferencia en la sostenibilidad del Centro de Recursos Justo Gonzalez.',
    'support_mission' => 'Apoya nuestra misión, preserva nuestro patrimonio y forma parte de algo significativo. ¡Únete hoy y ayúdanos a continuar con nuestra importante labor!',
    'join_us' => 'Unase a nosoutros',
    'catherine_gonzalez_profile' => 'Catherine Gonzalez ha realizado contribuciones significativas en el campo de la teología y el estudio de las tradiciones religiosas hispanas. Como académica y educadora destacada, su trabajo ha sido fundamental para avanzar en la comprensión de los problemas teológicos dentro de las comunidades latinas. A través de su investigación, escritos y enseñanzas, Gonzalez ha abordado temas como la intersección de género, cultura y fe, y ha destacado el papel de las mujeres en la configuración del discurso teológico.',
    'catherine_gonzalez_contributions' => 'La erudición de Gonzalez ha sido crucial para explorar cómo las perspectivas culturales y de género influyen en el pensamiento y la práctica teológica. Su compromiso con fomentar un entorno teológico más inclusivo y diverso ha ayudado a elevar las voces de los grupos marginados dentro del cristianismo. Al centrarse en las experiencias y contribuciones de las mujeres hispanas en la teología, ha ampliado la narrativa y enriquecido el diálogo académico en torno a estos temas cruciales.',
    'catherine_gonzalez_impact' => 'A través de sus esfuerzos educativos y mentoría, Catherine Gonzalez continúa inspirando y apoyando a la próxima generación de teólogos, animándolos a participar y contribuir a la rica tapestry de la teología hispana. Su dedicación a ampliar las perspectivas teológicas y promover la justicia social ha tenido un impacto duradero tanto en la comunidad académica como en la iglesia en general.',
    'catherine_gonzalez_achievements' => array(
        'pioneering_research' => '<strong>Investigación Pionera en Teología Hispana:</strong> Gonzalez ha realizado investigaciones innovadoras que exploran las intersecciones de género, cultura y fe dentro del contexto de las tradiciones religiosas hispánicas. Su trabajo ha sido fundamental para avanzar en la comprensión de estos temas y su impacto en el discurso teológico.',
        'influential_publications' => '<strong>Publicaciones Influyentes:</strong> Ha escrito varias obras significativas que han contribuido a la comunidad académica y teológica. Sus publicaciones a menudo abordan temas de identidad cultural y el papel de las mujeres en la teología, proporcionando valiosas perspectivas y fomentando una comprensión más profunda de estos temas importantes.',
        'advancing_gender_inclusivity' => '<strong>Avance en Inclusividad de Género:</strong> Gonzalez ha sido una defensora destacada de la inclusión de las voces y perspectivas femeninas en los estudios teológicos. Sus esfuerzos han ayudado a resaltar y abordar las disparidades de género dentro del campo, promoviendo un entorno académico más inclusivo y equitativo.',
        'educational_leadership' => '<strong>Liderazgo Educativo:</strong> Como educadora, Gonzalez ha desempeñado un papel crucial en la mentoría y formación de la próxima generación de teólogos. Su enseñanza y orientación han moldeado las carreras de muchos académicos, ayudándolos a navegar y contribuir al paisaje en evolución de la teología.',
        'promotion_of_social_justice' => '<strong>Promoción de la Justicia Social:</strong> Su trabajo se extiende más allá de la investigación académica para comprometerse activamente con los temas de justicia social. Gonzalez ha utilizado su plataforma para abogar por las comunidades marginadas y abordar las injusticias sistémicas dentro de las instituciones religiosas y académicas.',
        'collaborative_projects' => '<strong>Proyectos Colaborativos y Conferencias:</strong> Gonzalez ha participado y organizado varias conferencias académicas y proyectos colaborativos que reúnen a académicos de diversos orígenes para discutir y desarrollar nuevas perspectivas teológicas. Estas iniciativas han fomentado un mayor diálogo y comprensión dentro del campo.',
        'recognition_and_honors' => '<strong>Reconocimientos y Honores:</strong> Sus contribuciones a la teología y la educación han sido reconocidas a través de diversos premios y honores. Estos reconocimientos reflejan su impacto en la comunidad académica y su compromiso con el avance del estudio teológico.',
    ),
    'catherine_gonzalez_degrees' => array(
        'bachelor_of_arts' => '<strong>Bachillerato en Artes (B.A.):</strong> Obtuvo su título de pregrado en estudios religiosos en la Universidad de Harvard.',
        'master_of_divinity' => '<strong>Maestría en Divinidad (M.Div.):</strong> Completó su Maestría en Divinidad en la Escuela de Teología de Harvard.',
        'doctor_of_philosophy' => '<strong>Doctorado en Filosofía (Ph.D.):</strong> Obtuvo su Ph.D. en Teología en la Universidad de Princeton, con una tesis centrada en la teología de la liberación.',
        'honorary_degrees' => '<strong>Doctorados Honorarios:</strong> Ha recibido varios doctorados honorarios en reconocimiento a sus contribuciones a la teología y la educación teológica.',
    ),
    'catherine_gonzalez_honors' => array(
        'prestigious_awards' => '<strong>Premios Prestigiosos:</strong> Ha sido galardonada con numerosos premios en reconocimiento a su impacto en el campo de la teología y la justicia social.',
        'academic_organizations' => '<strong>Miembro de Organizaciones Académicas:</strong> Ha sido reconocida como miembro honorario de varias organizaciones académicas importantes, subrayando su influencia en el ámbito académico.',
        'public_recognition' => '<strong>Reconocimiento Público:</strong> Su trabajo ha sido destacado en diversas publicaciones académicas y medios de comunicación, reflejando su impacto y contribuciones a la teología y la justicia social.',
    ),
    'gonzalez_center_description' => array(
        'legacy_title' => '<strong>Creando un Legado de Excelencia Teológica</strong>',
        'legacy_description' => 'El Centro de Recursos Justo y Catherine Gonzalez se erige como un faro de excelencia en el estudio teológico latino, forjando un legado profundo en el ámbito de la fe y la exploración intelectual. Nombrado en honor a Justo y Catherine Gonzalez, el Centro encarna su compromiso con el avance de la comprensión teológica y la promoción de un entorno académico enriquecedor para los eruditos y practicantes latinos.',
        'majesty_title' => '<strong>Un Majestuoso Repositorio de Conocimientos</strong>',
        'majesty_description' => 'En el corazón del Centro Gonzalez se encuentra su majestuoso repositorio de recursos, cuidadosamente curado para apoyar y mejorar el estudio de la teología latina. La extensa colección del Centro abarca una amplia gama de temas, incluyendo teología histórica, teología de la liberación y estudios culturales, reflejando la profundidad y diversidad del pensamiento latino. Al proporcionar acceso a una gran cantidad de materiales académicos, el Centro permite a investigadores, estudiantes y teólogos explorar y comprometerse con las perspectivas matizadas que moldean las tradiciones cristianas latinas.',
        'contribution_title' => '<strong>Contribuyendo a la Teología Latina Hoy</strong>',
        'contribution_description' => 'El Centro Gonzalez desempeña un papel fundamental en la configuración de la teología latina hoy al servir como un centro central para la investigación y la educación teológica. A través de sus robustos programas y recursos, el Centro promueve el desarrollo de nuevas ideas teológicas y fomenta la exploración de cuestiones críticas dentro de las comunidades latinas. Sus iniciativas incluyen:
        <ul>
            <li><strong>Preservación y Promoción del Patrimonio Teológico Latino:</strong> El Centro protege el rico patrimonio teológico del cristianismo latino, asegurando que las obras y contribuciones significativas sean preservadas y accesibles para las generaciones futuras.</li>
            <li><strong>Apoyo a los Eruditos Emergentes:</strong> Al ofrecer apoyo en la investigación, mentoría y oportunidades de desarrollo profesional, el Centro fomenta a la próxima generación de teólogos y eruditos latinos, capacitándolos para hacer contribuciones significativas en el campo.</li>
            <li><strong>Fomento del Diálogo Académico:</strong> El Centro organiza conferencias, charlas y talleres que reúnen a eruditos, practicantes y líderes comunitarios para participar en un diálogo sobre cuestiones teológicas y sociales urgentes, fomentando una comunidad académica vibrante y colaborativa.</li>
            <li><strong>Ampliación del Acceso Educativo:</strong> A través de sus recursos digitales y programas educativos, el Centro expande el acceso a la educación teológica, haciendo posible que una audiencia más amplia se involucre con el pensamiento y la erudición teológica latina.</li>
        </ul>',
    ),

    'gonzalez_center_faq' => array(
        'question_1' => '<strong>¿Qué es el Centro de Recursos Justo y Catherine Gonzalez?</strong>',
        'answer_1' => 'El Centro de Recursos Justo y Catherine Gonzalez es una institución dedicada a preservar y promover el legado teológico y académico de Justo y Catherine Gonzalez. Proporciona acceso a una vasta colección de recursos, incluyendo libros, artículos y materiales relacionados con la teología hispana.',

        'question_2' => '<strong>¿Cómo puedo acceder a los recursos del Centro?</strong>',
        'answer_2' => 'Los recursos están disponibles en línea a través de nuestro sitio web. Para acceder a algunos materiales específicos, es posible que necesite credenciales especiales, que se pueden solicitar contactando al centro.',

        'question_3' => '<strong>¿Cuál es la misión del Centro de Recursos?</strong>',
        'answer_3' => 'Nuestra misión es promover y apoyar la contribución latina a la formación de líderes ministeriales a través del diálogo, los recursos educativos y la investigación, ayudando a expandir la comprensión de la teología hispana.',

        'question_4' => '<strong>¿Cómo puedo convertirme en "Amigo del Centro"?</strong>',
        'answer_4' => 'Puede convertirse en "Amigo del Centro" realizando una donación mensual o anual. Los detalles para inscribirse y contribuir están disponibles en nuestra página de "Amigos del Centro" en el sitio web.',

        'question_5' => '<strong>¿Cuáles son los beneficios de convertirse en "Amigo del Centro"?</strong>',
        'answer_5' => 'Como "Amigo del Centro", recibirá actualizaciones exclusivas, reconocimiento en nuestras publicaciones y sitio web, y acceso especial a eventos y nuevos recursos.',

        'question_6' => '<strong>¿El Centro organiza eventos o conferencias?</strong>',
        'answer_6' => 'Sí, el Centro organiza eventos, conferencias y seminarios web sobre temas relevantes para la teología hispana y el legado de Justo y Catherine Gonzalez. Las fechas y detalles se actualizan regularmente en nuestro sitio web.',

        'question_7' => '<strong>¿Dónde puedo encontrar los materiales y libros de Justo y Catherine Gonzalez?</strong>',
        'answer_7' => 'Los materiales y libros están disponibles en nuestra biblioteca en línea. Para acceder a obras específicas, utilice nuestra plataforma de investigación y catálogos digitales.',

        'question_8' => '<strong>¿Cómo puedo hacer una donación al Centro?</strong>',
        'answer_8' => 'Las donaciones se pueden hacer a través de nuestro sitio web, donde encontrará opciones para contribuciones únicas, mensuales o anuales. Las donaciones ayudan a mantener y expandir nuestros recursos y programas.',
    ),
    'ceo_description' => array(
        'title' => 'Ondina Gonzalez - Diretora',
        'description' => '<p>Ondina E. González es natural de Cuba, de donde emigró hacia los Estados Unidos con su familia cuando tenía menos de tres años de edad. Un año más tarde su familia se instaló en la ciudad de Rome, en Georgia, donde los padres de Ondina prestaron sus servicios en Berry College hasta su jubilación en la década de los 90.</p><p>El padre de Ondina, Jorge A. González, era especialista en el Antiguo Testamento; y su madre, Ondina S. González era muy activa entre las mujeres metodistas unidas tanto a nivel local como nacional. Luego, no ha de sorprendernos el que en su hogar abundara el interés tanto en el servicio como en la educación, y que por tanto esas dos pasiones hayan guiado la vida de Ondina.</p><p>Tras recibir al mismo tiempo un bachillerato en historia y una maestría en historia colonial de la América Latina, Ondina obtuvo otro título avanzado en finanzas internacionales de la American Graduate School of International Management, en Phoenix, Arizona. Regresando entonces a la historia, obtuvo su Ph.D. de la Universidad de Emory en el 2001.</p><p>A partir de entonces, Ondina ha enseñado en diversas escuelas –entre ellas, Agnes Scott College y la Universidad de Emory. En tiempos más recientes, se ha dedicado a servir como Directora del Centro de Recursos Justo y Catherine González, colaborando en este programa que es parte de la Asociación para la Educación Teológica Hispana.</p>',

    ),
    'getaccessdatabase' => '¡Obtén acceso ahora a nuestra Colección Digital!',
    'clickhere' => 'Haz clic aquí',
    'database_desc1' => '<b>Desbloquea un mundo de conocimiento y recursos</b> con acceso exclusivo a nuestra colección digital. Ya sea que estés investigando, aprendiendo o explorando, nuestros recursos digitales curados están aquí para apoyar tu viaje.',
    'database_desc2' => 'Beneficios del Acceso:',
    'database_desc3' => '<b>Archivos Extensos:</b> Explora una amplia gama de documentos, publicaciones y recursos multimedia.',
    'database_desc4' => '<b>Información Actualizada:</b> Mantente informado con las últimas actualizaciones y adiciones a nuestra colección.',
    'database_desc5' => '<b>Interfaz Amigable:</b> Navega y busca fácilmente los materiales que necesitas.',
    'database_desc6' => '<b>¡No te pierdas este valioso recurso!</b> Regístrate o Inicia sesión para comenzar a explorar nuestra colección digital hoy mismo.',
    'welcome_description' => array(
        'p1' => 'Bienvenidos',
        'p2' => 'Nos alegra mucho que hayas tomado el tiempo para visitarnos.',
        'p3' => 'Aquí encontrarás una gran cantidad de recursos para apoyarte en tu ministerio, tus estudios y en tu jornada personal de fe.',
        'p4' => 'Quizás nuestro recurso más accesible es la colección digital de las obras inéditas del Dr. Justo L. González y de aquellas que realizó con la Dra. Catherine G. González. Esta colección es un ejemplo tangible del importante legado que estos dos grandes líderes de la iglesia han creado a través de más de 60 años de dedicación a la vida de la iglesia y a la educación de sus líderes. Hasta ahora, sin embargo, hemos subido solo una parte de los cientos de documentos que el Centro posee.',
        'p5' => 'Explora este sitio web y conoce más sobre el trabajo que estamos haciendo. Lee sobre el Centro como un lugar de encuentro, un sitio para soñar con las múltiples maneras en que los latinos y las latinas pueden contribuir a la iglesia universal y un lugar donde se celebra y se honra la historia del impacto de los cristianos hispanos. Descubre los inicios del Centro como parte de AETH. Conoce a quienes guiamos el trabajo del Centro González y aprende cómo también puedes apoyar su labor.',
        'p6' => 'El acceso a estos maravillosos recursos que se encuentran en nuestra colección es mediante suscripción, la cual se puede adquirir a través de AETH o convirtiéndose en Amigo del Centro (ver abajo). Desplázate más abajo y encontrarás un ejemplo de uno de los documentos ya subidos a nuestra colección.',
        'p7' => 'Este estudio bíblico, publicado en El Discípulo, es uno de una serie de trece que abarca un trimestre completo de domingos. Ya hemos subido varias de estas series y están disponibles para aquellos que tienen acceso a la colección, y seguiremos subiendo más en el futuro.',
        'p8' => 'Para más ejemplos de algunos de nuestros recursos, por favor visita la página de Colecciones en este sitio web haciendo clic aquí.',
        'p9' => 'Para apoyar este importante legado y el trabajo del Centro creado en nombre de Justo y Catherine, hemos establecido el programa Amigos del Centro. Este programa es una vía para aquellos que creen en la necesidad de continuar y expandir el acceso al trabajo de los González, no solo a través de la colección digital, sino también mediante las innumerables maneras en que el Centro apoya y fomenta el trabajo de los líderes ministeriales en toda la iglesia.',
        'p10' => 'Haz clic aquí para saber más sobre el programa y las muchas maneras en que confiamos en los Amigos para guiar nuestro trabajo.',
        'p11' => 'Si prefieres hacer una donación única en lugar de un compromiso continuo con nuestro trabajo, por favor haz clic aquí para ser redirigido. Sepas que, de cualquier manera en que elijas ser parte del importante trabajo que estamos haciendo, agradecemos mucho tu donativo y humildemente pedimos tus oraciones.',
    ),

    'director' => 'Diretora',

    'junior' => array(
        'p1' => 'Wilson Fernandes Junior',
        'p2' => '<p>Conocido por muchos simplemente como Junior, es originario de Brasil y ha compartido una trayectoria de 26 años con su esposa, Keyla. Juntos han criado a sus dos hijos, Daniel (23) y Vitor (21), en el norte de Georgia desde 2018.</p><p>Desarrollador full stack de profesión, con un posgrado en Análisis y Desarrollo de Sistemas de la USP en Río de Janeiro, Brasil, y un título en Administración de Sistemas, Junior se dedica a crear soluciones digitales que satisfacen las necesidades del mundo dinámico de hoy. Sin embargo, su trabajo va más allá del ámbito tecnológico; su propósito más profundo es servir al Señor Jesucristo.</p><p>La pasión de Junior por la música se expresa a través de su papel como tecladista y líder de adoración en la Iglesia Brazil House en Johns Creek, GA. En esta función, lidera a otros en la adoración, ayudándolos a convertirse en una parte integral del cuerpo de Cristo y a seguir Su voluntad.</p><p>Su camino de fe comenzó a la edad de 12 años, y desde entonces se ha comprometido a difundir el mensaje de amor y esperanza. Sus esfuerzos han contribuido al establecimiento de iglesias tanto en Brasil como en los Estados Unidos.</p><p>Además de sus roles profesionales y ministeriales, Junior juega un papel vital en el Centro Justo, donde ha sido fundamental en el desarrollo de herramientas y procesos para digitalizar los vastos archivos del centro.</p>',
    ),
    'sophia' => array(
        'p1' => 'Sophia Porter',
        'p2' => '<p>Sophia Porter es pasante en el Centro de Recursos Justo y Catherine González, donde trabaja con el programa Amigos del Centro. Actualmente, es estudiante de la Maestría en Divinidad en la Candler School of Theology y vive en Atlanta, Georgia.</p><p> Nació y creció en Marion, Indiana, donde también realizó su carrera de pregrado. Se graduó de la Indiana Wesleyan University con especialidades en Desarrollo Comunitario y Ministerios Pastorales.</p><p>Después de su licenciatura, estudió lingüística española e historia en la Universidad de Nebrija en Madrid, España.</p><p>Aparte de sus estudios, le encanta pasar tiempo con su familia y amigos cercanos. Ha disfrutado mucho su tiempo en el Centro y espera continuar con el trabajo que se está realizando.</p>'
    ),
    'jessica' => array(
        'p1' => 'Dr. Jessica Lugo',
        'p2' => '<p>La Revda. Dra. Jessica Lugo Meléndez nació en San Juan, PR y creció en Deltona, Florida. Es una ministra ordenada de las Iglesias Bautistas Americanas y parte del cuerpo pastoral de las Iglesias Bautistas de Puerto Rico. Es profesora de Historia del Cristianismo, Nuevo Testamento y Evangelismo.</p><p>Con más de 20 años de experiencia ministerial y secular combinada, la Dra. Lugo ha escrito para diversas referencias teológicas, eclesiásticas y administrativas. Posee un Doctorado en Ministerio de Liberty University y un MDiv del Seminario Evangélico de Puerto Rico.</p><p>En 2024, la Dra. Lugo se convirtió en la novena Directora Ejecutiva de la Asociación para la Educación Teológica Hispana (AETH), supervisando sus más de cinco programas, incluido el Centro de Recursos Justo y Catherine González. Bajo su liderazgo, AETH ha ampliado sus esfuerzos para apoyar y fortalecer la educación teológica para hispanos.</p>'
    ),
    'donate' => 'Donar Ahora',
    'ourCollection' => 'Nuestra Colección',
    'friends_desc' => array(
        'p1' => 'Si deseas involucrarte más en el valioso trabajo que se lleva a cabo en el Centro de Recursos Justo y Catherine González, considera unirte a los Amigos del Centro. Nuestros Amigos son colaboradores vitales para mantener y mejorar nuestros recursos y programas. Esta asociación es invaluable para nuestro trabajo y ayuda a garantizar que los recursos del Centro puedan seguir siendo accesibles lo más ampliamente posible.',
        'p2' => 'Los Amigos del Centro son personas que apoyan el trabajo y la visión del Centro tanto financieramente como con sus comentarios, sugerencias y aportes.',
        'p3' => '<b>Aportes y sugerencias.</b> Como miembro de este grupo, tus aportes y sugerencias no solo son bienvenidos, sino que se buscan activamente. Para que tus comentarios sean significativos, recibirás actualizaciones periódicas sobre las actividades del Centro, así como acceso a la colección digital del Centro, que generalmente solo está disponible mediante suscripción, mientras sigas siendo un Amigo. A medida que leas lo que estamos haciendo o revises las colecciones digitales, esperamos que nos hagas saber de qué manera podemos mejorar, qué recursos deberíamos ofrecer y señalar errores que deban corregirse. (Para obtener más información sobre la colección digital, haz clic aquí.)',
        'p4' => '<b>Comunicación.</b> Como parte del programa de Amigos, también te enviaremos piezas mensuales para la reflexión. Estos breves ensayos son escritos por personas que, como tú, están en un viaje de fe, han trabajado o aún trabajan en algún tipo de ministerio y nos invitan a pensar más profundamente sobre varios aspectos de la fe. Algunos ensayos estarán relacionados con el calendario cristiano; en el tiempo ordinario, las reflexiones a menudo se enfocan en cómo y dónde podemos experimentar más de cerca a Dios. Ocasionalmente recurrimos a las palabras de quienes nos precedieron, como Isidoro de Sevilla, para leer pensamientos que han inspirado a muchos a lo largo de los años.',
        'p5' => '<b>Apoyo financiero.</b> Las personas que hacen una donación anual de $200.00 o más al Centro tendrán automáticamente una suscripción de un año al programa de Amigos. Aquellos que realicen donaciones mensuales recurrentes de $15 o más serán Amigos mientras continúe la contribución. Si deseas convertirte en Amigo del Centro, por favor contacta a Luz Ortiz por correo electrónico a lzortiz@aeth.org o por teléfono al 407-773-1234.',
        'p6' => 'Tu apoyo nos ayudará a mantener y expandir nuestra colección y nos permitirá ofrecer más materiales valiosos para la investigación y la educación. Así que considera hacer un impacto duradero uniéndote al programa de Amigos del Centro. Juegas un papel vital en la preservación y promoción del legado de Justo y Catherine González, asegurando que las futuras generaciones puedan seguir accediendo y aprendiendo de estos recursos invaluables.',
    ),

    'acervo_desc' => array(
        'p1' => '¿Alguna vez te has preguntado cómo acceder al trabajo de uno de los grandes líderes cristianos contemporáneos de la comunidad latina, uno de sus historiadores más importantes y uno de sus más exitosos promotores de la educación para líderes cristianos hispanos?',
        'p2' => '<b>Has encontrado el lugar:</b> La colección digital del Centro de Recursos Justo y Catherine González, un programa de la Asociación para la Educación Teológica Hispana. Aquí encontrarás una variedad de obras no publicadas del Dr. Justo L. González, como sermones, estudios bíblicos y conferencias, así como algunas de sus obras publicadas, incluidos estudios bíblicos en español. Aquí también encontrarás muchos de los escritos de la Dra. Catherine G. González, una de las mujeres pioneras en la educación teológica, --algunos de su autoría y otros en colaboración con Justo. Estos últimos recursos revelan claramente cómo los Dres. González han colaborado y se han apoyado mutuamente a lo largo de los años.',
        'p3' => 'A lo largo de sus más de sesenta años de carrera, los Dres. González han compartido sus pensamientos, análisis e interpretaciones sobre una amplia gama de temas que te inspirarán, informarán y desafiarán: leer la Biblia de nuevas maneras, encontrarse con el testimonio de la iglesia primitiva, reformar la educación teológica y practicar la justicia. Encontrarás todo eso y mucho más cobrando vida aquí. Así que navega, realiza búsquedas dirigidas, lee breves extractos de los documentos, aprende de dos de los líderes cristianos más importantes de hoy y vuelve con frecuencia, ya que constantemente estamos subiendo nuevos recursos.',
        'p4' => 'El acceso al sitio web está disponible solo para aquellos que se suscriban al Centro de Recursos Justo y Catherine González o sean Amigos del Centro. Para comprar una suscripción, por favor <a href="https://aeth.info/en/afiliacion" target="_blank">haz clic aquí</a>. Para obtener información sobre cómo convertirte en Amigo del Centro y ayudarnos a garantizar el acceso mundial al trabajo del Dr. González, por favor <a href="friend.php" target="_blank">haz clic aquí</a>.',
        'p5' => 'A continuación, sin embargo, hay dos ejemplos de documentos disponibles a través de nuestra colección digital. Esto debería darte una idea de lo que podrías encontrar si te conviertes en Amigo del Centro o suscriptor.',
        'p6' => 'Esta primera pieza, titulada “Los ‘Padres’ Hispanos”, es una de tres conferencias que Justo González dio en 2023 en un retiro de pastores hispanos en California. En ella, explora la historia del impacto de los “padres” españoles de la iglesia. Léelo por ti mismo. <a href="https://gonzalezcenter.s3.us-east-2.amazonaws.com/d_hisp_01394.pdf" target="_blank"><i class="fas fa-file-pdf"></i> Descargar aquí</a>. La segunda pieza es una conferencia titulada “La Señal de Jonás”, que explora la diversidad de la bondad y la creación de Dios. Aunque el enlace disponible aquí es para la versión en español, este documento también está disponible en inglés y portugués. <a href="https://gonzalezcenter.s3.us-east-2.amazonaws.com/d_sena_00005.pdf" target="_blank"><i class="fas fa-file-pdf"></i> Descargar aquí</a>.',
    ),

);

