<?php // lang_es.php
$lang = array(
    'home' => 'Home',
    'about' => 'Sobre Nosotros',
    'contact' => 'Contacto',
    'website_name' => 'COLAB Enriqueciendo a todas nuestras instituciones',
    'somosredet' => '#somosREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Comunidad de Práctica',
    'members' => 'Membresia',
    'news' => 'News',
    'membresias' => 'Membresías',
    'saber_mas' => 'Saber Más',
    'ser_miembro' => 'Ser Miembro',
    'ser_miembro_desc1' => 'Todos los miembros individuales e institucionales de AETH, interesados en la educación teológica hispana / latina (a), pueden ser miembros de ReDET. Cuentan con las siguientes categorías de miembros:',
    'ser_miembro_desc2' => '<b>Membresía de Personas:</b> Para mujeres y hombres que sirven como educadores en educación teológica; estudiantes matriculados en cualquier institución de educación teológica de pregrado, instituto bíblico o programa de capacitación ministerial; pastores o líderes de denominaciones e iglesias, o trabajadores de organizaciones religiosas o no gubernamentales, y otros interesados en la educación teológica.',
    'ser_miembro_desc3' => '<b>Membresía de Organizaciones:</b> Para Seminarios, Facultades de teología, Institutos bíblicos, empresas de servicio u organizaciones basadas en la fe.',
    'redet_name' => 'Red de Entidades Teológicas (ReDET)',
    'redet_desc1' => 'Expandiendo conexiones a través de la Educación teológica.',
    'redt_desc2' => '<b>ReDET</b> es una comunidad de personas y entidades creada para el apoyo mutuo, la colaboración y la solución de problemas comunes en la educación teológica.',
    'association' => 'Asociación para la Educación Teológica Hispana.',
    'lilly' => 'Lilly Endowment is a private foundation since 1937',
    'description' => 'REDET es una red dedicada a avanzar la educación teológica en toda América Latina. Proporciona recursos, oportunidades de colaboración y formación para apoyar a las instituciones en su misión de desarrollar líderes cristianos. Al fomentar asociaciones entre escuelas teológicas y promover la educación de calidad, REDET busca empoderar comunidades, mejorar el desarrollo del liderazgo y fortalecer el impacto del ministerio cristiano en la región.',
    'visit' => 'visitar',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',

);
