<?php // lang_en.php
$lang = array(
    'home' => 'Home',
    'about' => 'About Us',
    'contact' => 'Contact',
    'website_name' => 'COLAB Enriching all our institutions',
    'somosredet' => '#WeAreREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Community of Practice',
    'members' => 'Membership',
    'news' => 'News',
    'membresias' => 'Memberships',
    'saber_mas' => 'Learn More',
    'ser_miembro' => 'Become a Member',
    'ser_miembro_desc1' => 'All individual and institutional members of AETH, interested in Hispanic/Latino theological education, can become members of ReDET. They have the following membership categories:',
    'ser_miembro_desc2' => '<b>Individual Membership:</b> For men and women serving as educators in theological education; students enrolled in any undergraduate theological education institution, Bible institute, or ministerial training program; pastors or leaders of denominations and churches, or workers in religious or non-governmental organizations, and others interested in theological education.',
    'ser_miembro_desc3' => '<b>Organizational Membership:</b> For seminaries, theological faculties, Bible institutes, service companies, or faith-based organizations.',
    'redet_name' => 'Network of Theological Entities (ReDET)',
    'redet_desc1' => 'Expanding connections through theological education.',
    'redt_desc2' => '<b>ReDET</b> is a community of people and entities created for mutual support, collaboration, and problem-solving in theological education.',
    'association' => 'Association for Hispanic Theological Education.',
    'lilly' => 'Lilly Endowment is a private foundation since 1937',
    'description' => 'REDET is a network dedicated to advancing theological education throughout Latin America. It provides resources, opportunities for collaboration, and training to support institutions in their mission to develop Christian leaders. By fostering partnerships between theological schools and promoting quality education, REDET seeks to empower communities, enhance leadership development, and strengthen the impact of Christian ministry in the region.',
    'visit' => 'Visit',
    'nosotros' => 'ABOUT US',
    'about_desc1' => 'We are ReDET, people and entities dedicated to the theological formation of leaders for service to Hispanic and Latino communities. As one body, we form a collaborative movement where:',
    'about_desc2' => '1. We share our experience and knowledge to identify common needs and opportunities and to learn from one another.',
    'about_desc3' => '2. We seek to jointly resolve problems and overcome common barriers.',
    'about_desc4' => '3. We create and imagine opportunities to expand the reach and improve the quality of our ministries.',
    'about_desc5' => '4. We strive to develop conditions that, separately, are difficult to achieve, so that our work and teaching are more relevant to the communities we serve.',
    'about_desc6' => '5. We envision and innovate methodological and organizational alternatives so that our institutions and organizations become channels of service and signs of the Kingdom of God.',
    'about_mission' => 'Fostering collaboration among leaders of Hispanic Bible institutes and other theological training programs to jointly solve common problems and seize opportunities that result in increased students and graduates capable of serving the church and society in a relevant manner.',
    'about_vision' => 'To constitute a movement of people and entities committed to the constant and contextual improvement of Hispanic theological education programs so that our churches and organizations become channels of service and signs of the Kingdom of God in the world.',
    'vision' => 'Vision',
    'mission' => 'Mission',
    'elearning' => 'e-learning',
    'elearning_desc' => 'Provides instructional methods and interactive video presentations (e-Learning modules), focusing on the tools found in CoLAB.',
    'elearning_page_p1' => 'Resource',
    'elearning_page_p2' => 'ReDET’s first e-Learning modules are dedicated to strategic planning for Bible Institutes (BI), aiming for a higher standard of excellence in structure and content. The modules are in Spanish with English subtitles, and each video will last 15 to 30 minutes.',
    'elearning_page_p3' => '<b>e-Learning Module One:</b> Developing the mission, vision, and values statement (history)',
    'elearning_page_p4' => '<b>e-Learning Module Two:</b> Identifying problems and strategic objectives',
    'elearning_page_p5' => '<b>e-Learning Module Three:</b> Human resources',
    'elearning_page_p6' => '<b>e-Learning Module Four:</b> Operating budget',
    'elearning_page_p7' => '<b>e-Learning Module Five:</b> Hiring and marketing',
    'elearning_page_p8' => '<b>e-Learning Module Six:</b> Monitor and evaluate your strategic plan | Evaluate your strategic planning practices',
    'elearning_page_p9' => 'Consult resources',

    'plan' => 'Strategic Plan',
    'plan_desc' => 'Samples of strategic plans and valuable articles on the subject.',
    'plan_page1' => 'This catalog contains samples of strategic plans from ReDET member organizations. You will also find valuable articles on the topic written by other organizations.',
    'plan_page2' => '<a href="https://www.wartburgseminary.edu/download/strategic-plan-2017-2020/" target="blank">Wartburg Seminary</a>',
    'plan_page3' => '<a href="https://alban.org/category/strategic-planning/" target="blank">Alban Institute at Duke Divinity School</a>',
    'plan_page4' => '<a href="https://drive.google.com/drive/folders/14A8XSAXrDGAvplUYBYeuz9GHNHj5408p" target="blank">ReDET</a>',
    'recurso' => 'Resource',
    'liderasgo' => 'Leadership',
    'liderasgo_desc' => 'Valuable articles on the subject of leadership in a variety of contexts written by various authors and organizations.',
    'liderazgo_page1' => 'This catalog contains valuable articles on leadership in various contexts written by different authors and organizations.',
    'liderazgo_page2' => '<a href="https://alban.org/category/leadership/page/2/" target="blank">Alban Institute at Duke Divinity School</a>',
    'liderazgo_page3' => '<a href=" https://drive.google.com/file/d/1gVWuCEn8BFPPTfvVk0rcsMjLvDFwyVKO/view" target="blank"> IBIT Institutional Catalog</a>',

    'formation' => 'Spiritual Formation',
    'formation_desc' => 'Websites of organizations dedicated to spiritual formation in various settings and serving different communities.',
    'formation_p1' => 'This catalog contains websites of organizations dedicated to spiritual formation in various settings and serving different communities.',
    'formation_p2' => '<a href="https://www.redet.us/www.ashreimexico.net" target="blank">Ashrei Spiritual Formation</a>',
    'formation_p3' => '<a href="https://renovare.org/" target="blank">Renovaré</a>',
    'formation_p4' => '<a href="https://thecrucibleproject.org/" target="blank">The Crucible Project (Men/Women Retreats)</a>',
    'formation_p5' => '<a href="http://daretosoarcouples.com/" target="blank">Dare to Soar (Couples)</a>',



    'segunda' => 'Second Generation',
    'segunda_desc' => 'Resources addressing second-generation Hispanics/Latinos.',
    'segunda_p1' => 'This catalog contains podcasts aimed at mixed Hispanic/Latino people and the mixed church. The podcasts answer questions about the challenges of the first, second, and third generations of immigrants being part of, serving, and growing in an ethnic church.',
    'segunda_p2' => 'The Mestizo Podcast by World Outspoken.',
    'segunda_p3' => 'Podcasts aimed at mixed Hispanic/Latino people, the mixed church, and immigrant generations being part of, serving, and growing in an ethnic church. Each episode is released every Wednesday (for a total of 8 episodes). AETH members can subscribe to podcasts on any platform (Apple Podcast, Spotify, Google Podcast, and Stitcher) to ensure they don’t miss episodes.',

    'newcatalog' => 'Bible Institute Catalog',
    'newcatalog_desc' => 'Samples of strategic plans and valuable articles on the subject',
    'catalogo_p1' => 'This catalog contains samples of Bible institute catalogs from ReDET member institutes.',
    'catalogo_p2' => '<a href="http://ibitibi.org/wp-content/uploads/2019/07/Catalogo-de-IBIT-2019-2020.docx" target="blank">The International Biblical Institute of Texas</a>',

    'materiales' => 'Didactic Materials',
    'materiales_desc' => 'Websites and other sources offering useful information, articles, books, and other instructional materials.',
    'materiales_p1' => 'This catalog contains websites and other sources offering useful information, articles, books, and other instructional materials.',
    'materiales_p2' => '<a href="https://www.tallerteologicolatinoamericano.org/" target="blank">Latin American Theological Workshop</a>',
    'materiales_p3' => '<a href="https://gobierno.pr/sectors/religion" target="blank">Government of Puerto Rico</a>',

);
