<?php // lang_pt_br.php
$lang = array(
    'home' => 'Início',
    'about' => 'Sobre Nós',
    'contact' => 'Contato',
    'website_name' => 'CoLAB Enriquecendo Todas as Nossas Instituições',
    'somosredet' => '#SomosREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Comunidade de Prática',
    'members' => 'Membros',
    'news' => 'Notícias',
    'membresias' => 'Membresias',
    'saber_mas' => 'Saiba Mais',
    'ser_miembro' => 'Torne-se um Membro',
    'ser_miembro_desc1' => 'Todos os membros individuais e institucionais da AETH, interessados na educação teológica hispânica/latina, podem se tornar membros da ReDET. Eles têm as seguintes categorias de associação:',
    'ser_miembro_desc2' => '<b>Associação Individual:</b> Para homens e mulheres que atuam como educadores na educação teológica; estudantes matriculados em qualquer instituição de ensino teológico de graduação, instituto bíblico ou programa de treinamento ministerial; pastores ou líderes de denominações e igrejas, ou trabalhadores em organizações religiosas ou não governamentais, e outros interessados em educação teológica.',
    'ser_miembro_desc3' => '<b>Associação Organizacional:</b> Para seminários, faculdades teológicas, institutos bíblicos, empresas de serviços ou organizações baseadas na fé.',
    'redet_name' => 'Rede de Entidades Teológicas (ReDET)',
    'redet_desc1' => 'Expandindo Conexões Através da Educação Teológica.',
    'redet_desc2' => '<b>ReDET</b> é uma comunidade de pessoas e entidades criada para apoio mútuo, colaboração e resolução de problemas na educação teológica.',
    'association' => 'Associação para Educação Teológica Hispânica.',
    'lilly' => 'Lilly Endowment é uma fundação privada desde 1937',
    'description' => 'REDET é uma rede dedicada ao avanço da educação teológica em toda a América Latina. Ela fornece recursos, oportunidades de colaboração e treinamento para apoiar instituições em sua missão de desenvolver líderes cristãos. Ao promover parcerias entre escolas teológicas e incentivar uma educação de qualidade, a REDET busca capacitar comunidades, melhorar o desenvolvimento de liderança e fortalecer o impacto do ministério cristão na região.',
    'visit' => 'Visitar',
    'nosotros' => 'SOBRE NÓS',
    'about_desc1' => 'Nós somos a ReDET, pessoas e entidades dedicadas à formação teológica de líderes para servir às comunidades hispânicas e latinas. Como um corpo, formamos um movimento colaborativo onde:',
    'about_desc2' => '1. Compartilhamos nossa experiência e conhecimento para identificar necessidades e oportunidades comuns e aprender uns com os outros.',
    'about_desc3' => '2. Buscamos resolver em conjunto os problemas e superar barreiras comuns.',
    'about_desc4' => '3. Criamos e imaginamos oportunidades para expandir o alcance e melhorar a qualidade de nossos ministérios.',
    'about_desc5' => '4. Esforçamo-nos para desenvolver condições que, separadamente, são difíceis de alcançar, para que nosso trabalho e ensino sejam mais relevantes para as comunidades que servimos.',
    'about_desc6' => '5. Envisionamos e inovamos alternativas metodológicas e organizacionais para que nossas instituições e organizações se tornem canais de serviço e sinais do Reino de Deus.',
    'about_mission' => 'Promover a colaboração entre líderes de institutos bíblicos hispânicos e outros programas de formação teológica para resolver conjuntamente problemas comuns e aproveitar oportunidades que resultem em mais estudantes e graduados capazes de servir à igreja e à sociedade de maneira relevante.',
    'about_vision' => 'Constituir um movimento de pessoas e entidades comprometidas com a melhoria constante e contextual dos programas de educação teológica hispânica, para que nossas igrejas e organizações se tornem canais de serviço e sinais do Reino de Deus no mundo.',
    'vision' => 'Visão',
    'mission' => 'Missão',
    'elearning' => 'e-learning',
    'elearning_desc' => 'Oferece métodos de ensino e apresentações interativas em vídeo (módulos de e-Learning), com foco nas ferramentas encontradas no CoLAB.',
    'elearning_page_p1' => 'Recurso',
    'elearning_page_p2' => 'Os primeiros módulos de e-Learning da ReDET são dedicados ao planejamento estratégico para Institutos Bíblicos (IB), visando um padrão de excelência mais elevado em estrutura e conteúdo. Os módulos são em espanhol com legendas em inglês, e cada vídeo terá de 15 a 30 minutos.',
    'elearning_page_p3' => '<b>Módulo de e-Learning Um:</b> Desenvolvendo a missão, visão e declaração de valores (história)',
    'elearning_page_p4' => '<b>Módulo de e-Learning Dois:</b> Identificando problemas e objetivos estratégicos',
    'elearning_page_p5' => '<b>Módulo de e-Learning Três:</b> Recursos humanos',
    'elearning_page_p6' => '<b>Módulo de e-Learning Quatro:</b> Orçamento operacional',
    'elearning_page_p7' => '<b>Módulo de e-Learning Cinco:</b> Contratação e marketing',
    'elearning_page_p8' => '<b>Módulo de e-Learning Seis:</b> Monitorar e avaliar seu plano estratégico | Avaliar suas práticas de planejamento estratégico',
    'elearning_page_p9' => 'Consultar recursos',

    'plan' => 'Plano Estratégico',
    'plan_desc' => 'Amostras de planos estratégicos e artigos valiosos sobre o assunto.',
    'plan_page1' => 'Este catálogo contém amostras de planos estratégicos das organizações membros da ReDET. Você também encontrará artigos valiosos sobre o tema, escritos por outras organizações.',
    'plan_page2' => '<a href="https://www.wartburgseminary.edu/download/strategic-plan-2017-2020/" target="blank">Wartburg Seminary</a>',
    'plan_page3' => '<a href="https://alban.org/category/strategic-planning/" target="blank">Alban Institute at Duke Divinity School</a>',
    'plan_page4' => '<a href="https://drive.google.com/drive/folders/14A8XSAXrDGAvplUYBYeuz9GHNHj5408p" target="blank">ReDET</a>',
    'recurso' => 'Recurso',
    'liderasgo' => 'Liderança',
    'liderasgo_desc' => 'Artigos valiosos sobre o tema da liderança em diversos contextos, escritos por vários autores e organizações.',
    'liderazgo_page1' => 'Este catálogo contém artigos valiosos sobre liderança em diversos contextos, escritos por diferentes autores e organizações.',
    'liderazgo_page2' => '<a href="https://alban.org/category/leadership/page/2/" target="blank">Alban Institute at Duke Divinity School</a>',
    'liderazgo_page3' => '<a href="https://drive.google.com/file/d/1gVWuCEn8BFPPTfvVk0rcsMjLvDFwyVKO/view" target="blank">Catálogo Institucional do IBIT</a>',

    'formation' => 'Formação Espiritual',
    'formation_desc' => 'Sites de organizações dedicadas à formação espiritual em diversos contextos e servindo diferentes comunidades.',
    'formation_p1' => 'Este catálogo contém sites de organizações dedicadas à formação espiritual em diversos contextos e servindo diferentes comunidades.',
    'formation_p2' => '<a href="https://www.redet.us/www.ashreimexico.net" target="blank">Ashrei Formação Espiritual</a>',
    'formation_p3' => '<a href="https://renovare.org/" target="blank">Renovaré</a>',
    'formation_p4' => '<a href="https://thecrucibleproject.org/" target="blank">The Crucible Project (Retiros Masculinos/Femininos)</a>',
    'formation_p5' => '<a href="http://daretosoarcouples.com/" target="blank">Dare to Soar (Casais)</a>',

    'segunda' => 'Segunda Geração',
    'segunda_desc' => 'Recursos voltados para hispânicos/latinos de segunda geração.',
    'segunda_p1' => 'Este catálogo contém podcasts direcionados a pessoas hispânicas/latinas mistas e a igreja mista. Os podcasts respondem a perguntas sobre os desafios da primeira, segunda e terceira gerações de imigrantes sendo parte de, servindo e crescendo em uma igreja étnica.',
    'segunda_p2' => 'O Podcast Mestizo por World Outspoken.',
    'segunda_p3' => 'Podcasts direcionados a pessoas hispânicas/latinas mistas, à igreja mista e às gerações de imigrantes sendo parte de, servindo e crescendo em uma igreja étnica. Cada episódio é lançado toda quarta-feira (total de 8 episódios). Os membros da AETH podem ouvir gratuitamente, mas as opções de assinatura oferecem algumas vantagens adicionais (Spotify, Google).',

    'enlace' => 'Links de Interesse',
    'enlace_desc' => 'Recursos e sites de interesse das comunidades, e links úteis para organizações e governo.',
    'enlace_p1' => '<a href="https://revistapregao.com.br/" target="blank">Revista Pregão</a>',
    'enlace_p2' => '<a href="https://avanzar.com/" target="blank">Avanzar</a>',
    'enlace_p3' => '<a href="https://gobierno.pr/sectors/religion" target="blank">Governo de Porto Rico</a>',
);
