<?php
// lang_pt.php
$lang = array(
    'home' => 'Início',
    'about' => 'Sobre Nós',
    'contact' => 'Contato',
    'website_name' => 'COLAB Enriquecendo todas as nossas instituições',
    'somosredet' => '#somosREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Comunidade de Prática',
    'members' => 'Membros',
    'news' => 'Notícias',
    'membresias' => 'Membros',
    'saber_mas' => 'Saiba Mais',
    'ser_miembro' => 'Seja Membro',
    'ser_miembro_desc1' => 'Todos os membros individuais e institucionais da AETH, interessados na educação teológica hispânica / latina, podem ser membros da ReDET. Existem as seguintes categorias de membros:',
    'ser_miembro_desc2' => '<b>Membresia de Pessoas:</b> Para homens e mulheres que atuam como educadores em educação teológica; estudantes matriculados em qualquer instituição de educação teológica de graduação, instituto bíblico ou programa de treinamento ministerial; pastores ou líderes de denominações e igrejas, ou trabalhadores de organizações religiosas ou não governamentais, e outros interessados na educação teológica.',
    'ser_miembro_desc3' => '<b>Membresia de Organizações:</b> Para seminários, faculdades de teologia, institutos bíblicos, empresas de serviços ou organizações baseadas na fé.',
    'redet_name' => 'Rede de Entidades Teológicas (ReDET)',
    'redet_desc1' => 'Expandindo conexões através da Educação Teológica.',
    'redt_desc2' => '<b>ReDET</b> é uma comunidade de pessoas e entidades criada para apoio mútuo, colaboração e solução de problemas comuns na educação teológica.',
    'association' => 'Associação para a Educação Teológica Hispânica.',
    'lilly' => 'Lilly Endowment é uma fundação privada desde 1937',
    'description' => 'REDET é uma rede dedicada ao avanço da educação teológica em toda a América Latina. Proporciona recursos, oportunidades de colaboração e formação para apoiar as instituições na sua missão de formar líderes cristãos. Ao promover parcerias entre escolas teológicas e melhorar a qualidade da educação, a REDET busca empoderar comunidades, melhorar o desenvolvimento de liderança e fortalecer o impacto do ministério cristão na região.',
    'visit' => 'visitar',
    'nosotros' => 'SOBRE NÓS',
    'about_desc1' => 'Somos ReDET, pessoas e entidades dedicadas à formação teológica de líderes para o serviço às comunidades hispânicas e latinas que, como um só corpo, formam um movimento de colaboração onde:',
    'about_desc2' => '1. Compartilhamos nossa experiência e conhecimento para identificar necessidades e oportunidades comuns e aprender uns com os outros.',
    'about_desc3' => '2. Buscamos resolver juntos problemas e superar barreiras que temos em comum.',
    'about_desc4' => '3. Criamos e imaginamos oportunidades para expandir o alcance e elevar a qualidade de nossos ministérios.',
    'about_desc5' => '4. Procuramos desenvolver as condições que, individualmente, são difíceis de alcançar, para que nosso trabalho e ensino sejam mais relevantes para as comunidades a que servimos.',
    'about_desc6' => '5. Visionamos e inovamos alternativas metodológicas e organizacionais para que nossas instituições e organizações sejam canais de serviço e sinais do Reino de Deus.',
    'about_mission' => 'Promover a colaboração entre líderes de institutos bíblicos hispânicos e outros programas de formação teológica para resolver problemas comuns e aproveitar oportunidades que permitam mudanças que resultem no aumento de estudantes e graduados capazes de servir à igreja e à sociedade de maneira relevante.',
    'about_vision' => 'Constituir um movimento de pessoas e entidades comprometidas com a melhoria constante e contextual dos programas de educação teológica hispânica, para que nossas igrejas e organizações sejam canais de serviço e sinais do Reino de Deus no mundo.',
    'vision' => 'Visão',
    'mission' => 'Missão',
    'elearning' => 'e-learning',
    'elearning_desc' => 'Fornece métodos de instrução e apresentações de vídeo interativas (módulos de e-learning), focadas nas ferramentas encontradas no coLAB.',
    'elearning_page_p1' => 'Recurso',
    'elearning_page_p2' => 'Os primeiros módulos de e-learning da ReDET são dedicados ao planejamento estratégico para Institutos Bíblicos (IB), buscando um maior padrão de excelência na estrutura e no conteúdo. Os módulos estão em espanhol com legendas em inglês, e cada vídeo terá duração de 15 a 30 minutos.',
    'elearning_page_p3' => '<b>Módulo um de e-learning:</b> Desenvolvimento da declaração de missão, visão e valores (história)',
    'elearning_page_p4' => '<b>Módulo dois de e-learning:</b> Identificação de problemas e objetivos estratégicos',
    'elearning_page_p5' => '<b>Módulo três de e-learning:</b> Recursos humanos',
    'elearning_page_p6' => '<b>Módulo quatro de e-learning:</b> Orçamento operacional',
    'elearning_page_p7' => '<b>Módulo cinco de e-learning:</b> Recrutamento e marketing',
    'elearning_page_p8' => '<b>Módulo seis de e-learning:</b> Supervisione e avalie seu plano estratégico | Avalie suas práticas de planejamento estratégico',
    'elearning_page_p9' => 'Consultar recursos',

    'plan' => 'Plano Estratégico',
    'plan_desc' => 'Exemplos de planos estratégicos e artigos valiosos sobre o tema.',
    'plan_page1' => 'Este catálogo contém exemplos de planos estratégicos de organizações membros da ReDET. Além disso, encontrará artigos valiosos sobre o tema escritos por outras organizações.',
    'plan_page2' => '<a href="https://www.wartburgseminary.edu/download/strategic-plan-2017-2020/" target="blank">Seminário Wartburg</a>',
    'plan_page3' => '<a href="https://alban.org/category/strategic-planning/" target="blank">Instituto Alban no Duke Divinity School</a>',
    'plan_page4' => '<a href="https://drive.google.com/drive/folders/14A8XSAXrDGAvplUYBYeuz9GHNHj5408p" target="blank">ReDET</a>',
    'recurso' => 'Recurso',
'liderasgo' => 'Liderança',
'liderasgo_desc' => 'Artigos valiosos sobre o tema da liderança em uma variedade de contextos escritos por diversos autores e organizações.',
'liderazgo_page1' => 'Este catálogo contém artigos valiosos sobre o tema da liderança em uma variedade de contextos escritos por diversos autores e organizações.',
'liderazgo_page2' => '<a href="https://alban.org/category/leadership/page/2/" target="blank">Alban Institute at Duke Divinity School</a>',
'liderazgo_page3' => '<a href="https://drive.google.com/file/d/1gVWuCEn8BFPPTfvVk0rcsMjLvDFwyVKO/view" target="blank">Catálogo Institucional IBIT</a>',

'formation' => 'Formação Espiritual',
'formation_desc' => 'Sites de organizações dedicadas à formação espiritual em uma variedade de ambientes e ao serviço de diferentes comunidades.',
'formation_p1' => 'Este catálogo contém os sites de organizações dedicadas à formação espiritual em uma variedade de ambientes e ao serviço de diferentes comunidades.',
'formation_p2' => '<a href="https://www.redet.us/www.ashreimexico.net" target="blank">Ashrei Formação Espiritual</a>',
'formation_p3' => '<a href="https://renovare.org/" target="blank">Renovaré</a>',
'formation_p4' => '<a href="https://thecrucibleproject.org/" target="blank">The Crucible Project (Retiro para Homens/Mulheres)</a>',
'formation_p5' => '<a href="http://daretosoarcouples.com/" target="blank">Dare to Soar (Casais)</a>',

'segunda' => 'Segunda Geração',
'segunda_desc' => 'Recursos que abordam hispânicos / latinos de segunda geração.',
'segunda_p1' => 'Este catálogo contém podcasts dirigidos a pessoas mistas hispânicas / latinas e à igreja mista. Os podcasts respondem perguntas sobre os desafios da primeira, segunda e terceira geração de imigrantes, sendo parte, servindo e crescendo em uma igreja étnica.',
'segunda_p2' => 'The Mestizo Podcast por World Outspoken.',
'segunda_p3' => 'Podcasts dirigidos a pessoas mistas hispânicas / latinas, à igreja mista e à geração de imigrantes, sendo parte, servindo e crescendo em uma igreja étnica. Cada um dos episódios é publicado toda quarta-feira (totalizando 8 episódios). Membros da AETH podem se inscrever nos podcasts em qualquer plataforma (Apple Podcast, Spotify, Google Podcast e Stitcher) para não perder os episódios.',

'newcatalog' => 'Catálogo de Instituto Bíblico',
'newcatalog_desc' => 'Amostras de planos estratégicos e artigos valiosos sobre o tema',
'catalogo_p1' => 'Este catálogo contém amostras de catálogos de institutos bíblicos membros da ReDET.',
'catalogo_p2' => '<a href="http://ibitibi.org/wp-content/uploads/2019/07/Catalogo-de-IBIT-2019-2020.docx" target="blank">O Instituto Bíblico Internacional do Texas</a>',

'materiales' => 'Materiais Didáticos',
'materiales_desc' => 'Sites e outras fontes que oferecem informações úteis, artigos, livros e outros materiais para a instrução.',
'materiales_p1' => 'Este catálogo contém sites e outras fontes que oferecem informações úteis, artigos, livros e outros materiais para a instrução.',
'materiales_p2' => '<a href="https://www.tallerteologicolatinoamericano.org/" target="blank">Taller Teológico Latinoamericano</a>',
'materiales_p3' => '<a href="https://bibleproject.com/" target="blank">Bible Project</a>',
'materiales_p4' => '<a href="https://www.tallerteologicolatinoamericano.org/" target="blank">Taller Teológico Latinoamericano</a>',
'materiales_p5' => '<a href="https://ibitibi.org/en/start-home-page" target="blank">Instituto Bíblico Internacional do Texas</a>',
'materiales_p6' => '<a href="https://redinbi.org/" target="blank">Graduate School of Theology</a>',

'materiales_inter' => 'Materiais Interculturais',
'materiales_inter_desc' => 'Sites e outras fontes com foco intercultural.',
'materialesinter_p1' => 'Este catálogo contém sites e outras fontes com foco intercultural.',
'materialesinter_p2' => '<a href="http://www.missiology.org/" target="blank">Missiology</a>',
'materialesinter_p3' => '<a href="https://missionalive.org/" target="blank">Mission Alive</a>',

'desarollo' => 'Desenvolvimento Organizacional',
'desarollo_desc' => 'Sites e artigos sobre análise PESTEL.',
'desarollo_p1' => 'Este catálogo contém sites e artigos sobre análise PESTEL: variáveis políticas, econômicas, sociais, tecnológicas, ecológicas e legais que afetam o objeto de estudo a partir de seu ambiente mais distante.',
'desarollo_p2' => '<a href="http://www.ncd-international.org/" target="blank">National Church Development (NCD)</a>',
'desarollo_p3' => '<a href="https://www.thebowencenter.org/introduction-eight-concepts" target="blank">The Bowen Center for the Study of the Family</a>',

'sistema' => 'Sistema de Gestão de Aprendizagem',
'sistema_desc' => 'Sites e informações sobre sistemas de gestão do aprendizado virtual.',
'sistema_p1' => 'Este catálogo contém sites e informações sobre sistemas de gestão do aprendizado virtual.',
'sistema_p2' => '<a href="https://www.d2l.com/products/learning-environment/" target="blank">D2L – Desire to Learn: Brightspace Learning Environment</a>',
'sistema_p3' => '<a href="https://360.articulate.com/" target="blank">Articulate</a>',
'sistema_p4' => '<a href="https://moodle.com/" target="blank">Moodle</a>',
'sistema_p5' => '<a href="https://www.instructure.com/canvas" target="blank">Canvas</a>',
'sistema_p6' => '<a href="https://www.blackboard.com/" target="blank">Blackboard</a>',

'colaboracion' => 'Colaboração digital de biblioteca',
'colaboracion_desc' => 'Sites e informações sobre plataformas digitais para o intercâmbio de recursos e de colaboração interbibliotecária.',
'colaboracion_p1' => 'Este catálogo contém sites e informações sobre plataformas digitais para o intercâmbio de recursos e de colaboração interbibliotecária. (Sua instituição deve ter autorização prévia para utilizar estas aplicações)',
'colaboracion_p2' => '<a href="https://www.atla.com/" target="blank">American Theological Library Association</a>',
'colaboracion_p3' => '<a href="https://www.digitaliapublishing.com/" target="blank">Digitalia Hispânica</a>',
'colaboracion_p4' => '<a href="https://libguides.thedtl.org/home" target="blank">Digital Theological Library</a>',
'colaboracion_p5' => '<a href="https://libguides.thedtl.org/oadtl" target="blank">Open Access Digital Theological Library</a>',
'colaboracion_p6' => '<a href="https://drive.google.com/file/d/1PnlrHZex8IZ0HkEmXWMBu65o7LxgzAby/view" target="blank">Currículo</a>',
'colaboracion_p7' => '<a href="https://drive.google.com/file/d/1JrkCM4pe4SGFpg7jnbqIrn50uuenv3QC/view" target="blank">A Igreja Hispana/Latina nos Estados Unidos</a>',
'colaboracion_p8' => '<a href="https://drive.google.com/file/d/17-I7IYvIcxAvv3AeJHrmxBenql7F9GcW/view" target="blank">Tópicos Variados</a>',

'libreria' => 'Livraria Virtual AETH',
'libreria_desc' => 'A livraria AETH oferece recursos para a educação e liderança teológica hispânica.',

'colab_1' => 'Colaborar | Contribuir | Conectar',
'colab_2' => 'BIBLIOTECA VIRTUAL ReDET',
'comunidad_desc1' => 'ReDET cria projetos comuns para o enriquecimento de todas as nossas instituições. Este tipo de colaboração torna possível o que sozinhos não podemos fazer, mas juntos podemos alcançar. Há muitas possibilidades diante de nós como ReDET e juntos sonhamos com as novas coisas que nos farão excelentes e eficazes educadores teológicos, seja em um instituto, igreja, centro, seminário, faculdade ou universidade.',
'comunidad_desc2' => 'Nosso primeiro projeto é uma plataforma digital interativa de assinatura online ReDET que incluirá um sistema de código aberto em documentos de desenvolvimento organizacional (ou seja, planejamento estratégico, operações e finanças). Este projeto foi realizado com a participação e colaboração de diversos institutos bíblicos. Além disso, a ReDET planeja continuar com o projeto da “Livraria Virtual AETH”, para promover e distribuir os livros de nossos membros e um catálogo de instituições e recursos oferecidos por nossas organizações. Se você tem interesse em participar, por favor, entre em contato conosco.',
'comunidad_desc3' => 'Os institutos desenvolverão e disponibilizarão, por escrito, estatutos/regulamentos e documentos comparáveis que definam os níveis de responsabilidade institucional, assim como documentos legais e a autorização dos órgãos de acreditação eclesiais, governamentais e educacionais aplicáveis. Esses documentos devem ser revisados periodicamente para verificar sua conformidade. (Manual de certificação da AETH, p. 9).',
'comunidad_desc4' => 'O propósito geral deste projeto é construir os meios (veículos) e a capacidade de colaboração entre os Institutos Bíblicos Hispanos e programas semelhantes de capacitação teológica de líderes de igrejas hispanas, criando uma rede de colaboração que possa trabalhar para resolver problemas comuns, inovação e trabalhar em projetos conjuntos que melhorem a qualidade de seu funcionamento e elevem os níveis de matrícula e formados.',
'clickaccess' => 'Clique aqui para acessar os recursos da ReDET',
'member_p1' => 'Como se tornar membro da ReDET?',
'member_p2' => 'Em abril de 2017, a Assembleia extraordinária da AETH ratificou de maneira unânime a necessidade de formar a ReDET e a estabeleceu como uma de suas prioridades estratégicas. Com a criação da ReDET, a AETH tomou a iniciativa de facilitar o encontro, a sinergia e a colaboração entre pessoas e entidades dedicadas à educação teológica hispana, interessadas na busca conjunta de soluções para problemas comuns, superando barreiras que compartilham e identificando as contribuições particulares que cada um está fazendo.',
'member_p3' => 'Membros individuais ou institucionais da AETH podem ampliar seus benefícios e seu potencial para transformar a educação teológica, tornando-se também membros da ReDET. Para isso, devem preencher o formulário correspondente – para pessoa ou para organização – que se encontra nesta página. Receberão uma resposta à sua solicitação, uma vez que a ReDET corrobore que cumprem os requisitos. Na resposta, encontrarão as instruções para ativar sua associação.',
'faq_q1' => 'Membresia individual da ReDET',
'faq_a1' => '<p>AETH reconhece que dentro de seus membros há pessoas dispostas a identificar as contribuições particulares que cada um está fazendo e comprometidas a buscar conjuntamente soluções para problemas e barreiras comuns em programas de educação teológica hispana. Por isso, é importante que membros da AETH se unam à ReDET se:</p>
<p>Possuem estudos formais na área da educação teológica ou em áreas relacionadas à educação e à administração de instituições educativas,</p>
<p>Ou têm ampla experiência dirigindo programas de formação educativa, dentro e fora do campo teológico-pastoral.</p>
<p>Se você é uma dessas pessoas, convidamos você a fortalecer a ReDET com seu conhecimento e experiência.</p>
<p>Seu aporte é necessário para transformar a situação.</p>
<p><strong>Faça parte da ReDET!</strong></p><p><a href="https://aeth.info/afiliacion" target="blank">Página de membresia da AETH</a>',

'faq_q2' => 'Membresia institucional da ReDET',
'faq_a2' => '<p>AETH reconhece que dentro de seus membros há pessoas dispostas a identificar as contribuições particulares que cada um está fazendo e comprometidas a buscar conjuntamente soluções para problemas e barreiras comuns em programas de educação teológica hispana. Por isso, é importante que membros da AETH se unam à ReDET se:</p>
<p>Possuem estudos formais na área da educação teológica ou em áreas relacionadas à educação e à administração de instituições educativas,</p>
<p>Ou têm ampla experiência dirigindo programas de formação educativa, dentro e fora do campo teológico-pastoral.</p>
<p>Se você é uma dessas pessoas, convidamos você a fortalecer a ReDET com seu conhecimento e experiência.</p>
<p>Seu aporte é necessário para transformar a situação.</p>
<p><strong>Faça parte da ReDET!</strong></p><p><a href="https://aeth.info/afiliacion" target="blank">Página de membresia da AETH</a>',

);
