<?php // lang_en.php
$lang = array(
    'home' => 'Home',
    'about' => 'About Us',
    'contact' => 'Contact',
    'website_name' => 'COLAB Enriching all our institutions',
    'somosredet' => '#weareREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Community of Practice',
    'members' => 'Membership',
    'news' => 'News',
    'membresias' => 'Memberships',
    'saber_mas' => 'Learn More',
    'ser_miembro' => 'Become a Member',
    'ser_miembro_desc1' => 'All individual and institutional members of AETH interested in Hispanic/Latino theological education can become members of ReDET. They have the following categories of membership:',
    'ser_miembro_desc2' => '<b>Individual Membership:</b> For men and women serving as educators in theological education; students enrolled in any undergraduate theological education institution, biblical institute, or ministerial training program; pastors or leaders of denominations and churches, or workers from religious or non-governmental organizations, and others interested in theological education.',
    'ser_miembro_desc3' => '<b>Organizational Membership:</b> For seminaries, faculties of theology, biblical institutes, service companies, or faith-based organizations.',
    'redet_name' => 'Network of Theological Entities (ReDET)',
    'redet_desc1' => 'Expanding connections through theological education.',
    'redt_desc2' => '<b>ReDET</b> is a community of people and entities created for mutual support, collaboration, and solving common problems in theological education.',
    'association' => 'Association for Hispanic Theological Education.',
    'lilly' => 'Lilly Endowment is a private foundation since 1937',
    'description' => 'REDET is a network dedicated to advancing theological education throughout Latin America. It provides resources, collaboration opportunities, and training to support institutions in their mission of developing Christian leaders. By fostering partnerships between theological schools and promoting quality education, REDET seeks to empower communities, enhance leadership development, and strengthen the impact of Christian ministry in the region.',
    'visit' => 'visit',
    'nosotros' => 'US',
    'about_desc1' => 'We are ReDET, people and entities dedicated to the theological formation of leaders for service to Hispanic and Latino communities, who, as one body, form a collaborative movement in which:',
    'about_desc2' => '1. We share our experience and knowledge to identify common needs and opportunities, and to learn from each other.',
    'about_desc3' => '2. We seek to jointly solve problems and overcome barriers we have in common.',
    'about_desc4' => '3. We create and imagine opportunities to expand our reach and elevate the quality of our ministries.',
    'about_desc5' => '4. We strive to develop conditions that are difficult to achieve separately, so that our work and teaching are more relevant to the communities we serve.',
    'about_desc6' => '5. We envision and innovate methodological and organizational alternatives so that our institutions and organizations are channels of service and signs of the Kingdom of God.',
    'about_mission' => 'Foster collaboration among leaders of Hispanic biblical institutes and other theological training programs to jointly solve common problems and seize opportunities for changes that result in an increase in students and graduates capable of serving the church and society in a relevant way.',
    'about_vision' => 'To constitute a movement of people and entities committed to the continuous and contextual improvement of Hispanic theological education programs so that our churches and organizations are channels of service and signs of the Kingdom of God in the world.',
    'vision' => 'Vision',
    'mission' => 'Mission',
    'elearning' => 'e-learning',
    'elearning_desc' => 'Provides instructional methods and interactive video presentations (e-Learning modules), focusing on the tools found in CoLAB.',
    'elearning_page_p1' => 'Resource',
    'elearning_page_p2' => 'The first e-Learning modules of ReDET are dedicated to strategic planning for Biblical Institutes (IB), seeking a higher standard of excellence within the structure and content. The modules are in Spanish with English subtitles, and each video will last between 15 and 30 minutes.',
    'elearning_page_p3' => '<b>e-Learning Module One:</b> Development of the mission, vision, and values statement (history)',
    'elearning_page_p4' => '<b>e-Learning Module Two:</b> Identification of problems and strategic objectives',
    'elearning_page_p5' => '<b>e-Learning Module Three:</b> Human resources',
    'elearning_page_p6' => '<b>e-Learning Module Four:</b> Operating budget',
    'elearning_page_p7' => '<b>e-Learning Module Five:</b> Hiring and marketing',
    'elearning_page_p8' => '<b>e-Learning Module Six:</b> Monitor and evaluate your strategic plan | Assess your strategic planning practices',
    'elearning_page_p9' => 'Consult resources',

    'plan' => 'Strategic Plan',
    'plan_desc' => 'Samples of strategic plans and valuable articles on the subject.',
    'plan_page1' => 'This catalog contains samples of strategic plans from ReDET member organizations. Additionally, you will find valuable articles on the subject written by other organizations.',
    'plan_page2' => '<a href="https://www.wartburgseminary.edu/download/strategic-plan-2017-2020/" target="blank">Wartburg Seminary</a>',
    'plan_page3' => '<a href="https://alban.org/category/strategic-planning/" target="blank">Alban Institute at Duke Divinity School</a>',
    'plan_page4' => '<a href="https://drive.google.com/drive/folders/14A8XSAXrDGAvplUYBYeuz9GHNHj5408p" target="blank">ReDET</a>',
    'recurso' => 'Resource',
    'liderasgo' => 'Leadership',
    'liderasgo_desc' => 'Valuable articles on the topic of leadership in a variety of contexts written by various authors and organizations.',
    'liderazgo_page1' => 'This catalog contains valuable articles on the topic of leadership in a variety of contexts written by various authors and organizations',
    'liderazgo_page2' => '<a href="https://alban.org/category/leadership/page/2/" target="blank">Alban Institute at Duke Divinity School</a>',
    'liderazgo_page3' => '<a href=" https://drive.google.com/file/d/1gVWuCEn8BFPPTfvVk0rcsMjLvDFwyVKO/view" target="blank"> Institutional Catalog IBIT</a>',

    'formation' => 'Spiritual Formation',
    'formation_desc' => 'Websites of organizations dedicated to spiritual formation in a variety of settings and serving different communities.',
    'formation_p1' => 'This catalog contains websites of organizations dedicated to spiritual formation in a variety of settings and serving different communities.',
    'formation_p2' => '<a href="https://www.redet.us/www.ashreimexico.net" target="blank">Ashrei Spiritual Formation </a>',
    'formation_p3' => '<a href="https://renovare.org/" target="blank">Renovaré </a>',
    'formation_p4' => '<a href="https://thecrucibleproject.org/" target="blank">The Crucible Project (Men/Women Retreats) </a>',
    'formation_p5' => '<a href="http://daretosoarcouples.com/" target="blank">Dare to Soar (Couples) </a>',

    'segunda' => 'Second Generation',
    'segunda_desc' => 'Resources addressing second-generation Hispanics/Latinos.',
    'segunda_p1' => 'This catalog contains podcasts aimed at mixed Hispanic/Latino individuals and the mixed church. The podcasts answer questions about the challenges faced by the first, second, and third generations of immigrants, being part of, serving, and growing in an ethnic church.',
    'segunda_p2' => 'The Mestizo Podcast by World Outspoken.',
    'segunda_p3' => 'Podcasts aimed at mixed Hispanic/Latino individuals, the mixed church, and the immigrant generation, being part of, serving, and growing in an ethnic church. Each episode is published every Wednesday (for a total of 8 episodes). AETH members can subscribe to the podcasts on any platform (Apple Podcast, Spotify, Google Podcast, and Stitcher) so they don’t miss the episodes.',

    'newcatalog' => 'Biblical Institute Catalog',
    'newcatalog_desc' => 'Samples of strategic plans and valuable articles on the subject.',
    'catalogo_p1' => 'This catalog contains samples of catalogs from biblical institutes that are members of ReDET.',
    'catalogo_p2' => '<a href="http://ibitibi.org/wp-content/uploads/2019/07/Catalogo-de-IBIT-2019-2020.docx" target="blank">The International Biblical Institute of Texas </a>',

    'materiales' => 'Teaching Materials',
    'materiales_desc' => 'Websites and other sources offering useful information, articles, books, and other materials for instruction.',
    'materiales_p1' => 'This catalog contains websites and other sources offering useful information, articles, books, and other materials for instruction.',
    'materiales_p2' => '<a href="https://www.biblicaltraining.org/ " target="blank">Biblical Training</a>',
    'materiales_p3' => '<a href="https://www.biblegateway.com/ " target="blank">Bible Gateway</a>',
    'materiales_p4' => '<a href="https://www.bible.com/ " target="blank">YouVersion</a>',
    'materiales_p5' => '<a href="https://bibles.org/ " target="blank">United Bible Societies</a>',
    'materiales_p6' => '<a href="https://www.theology.edu/ " target="blank">Theological Resources</a>',

    'development' => 'Organizational Development',
    'development_desc' => 'Websites and articles on PESTEL analysis.',
    'development_p1' => 'This catalog contains websites and articles on PESTEL analysis: political, economic, social, technological, ecological, and legal variables that affect the subject of study from its most distant environment.',
    'development_p2' => '<a href="http://www.ncd-international.org/" target="blank">National Church Development (NCD)</a>',
    'development_p3' => '<a href="https://www.thebowencenter.org/introduction-eight-concepts" target="blank">The Bowen Center for the Study of the Family</a>',

    'system' => 'Learning Management System',
    'system_desc' => 'Websites and information on virtual learning management systems.',
    'system_p1' => 'This catalog contains websites and information on virtual learning management systems.',
    'system_p2' => '<a href="https://www.d2l.com/products/learning-environment/" target="blank">D2L – Desire to Learn: Brightspace Learning Environment</a>',
    'system_p3' => '<a href="https://360.articulate.com/" target="blank">Articulate</a>',
    'system_p4' => '<a href="https://moodle.com/" target="blank">Moodle</a>',
    'system_p5' => '<a href="https://www.instructure.com/canvas" target="blank">Canvas</a>',
    'system_p6' => '<a href="https://www.blackboard.com/" target="blank">Blackboard</a>',

    'digital_collaboration' => 'Digital Library Collaboration',
    'digital_collaboration_desc' => 'Websites and information on digital platforms for resource sharing and interlibrary collaboration.',
    'digital_collaboration_p1' => 'This catalog contains websites and information on digital platforms for resource sharing and interlibrary collaboration. (Your institution must have prior authorization to use these applications)',
    'digital_collaboration_p2' => '<a href="https://www.atla.com/" target="blank">American Theological Library Association</a>',
    'digital_collaboration_p3' => '<a href="https://www.digitaliapublishing.com/" target="blank">Digitalia Hispánica</a>',
    'digital_collaboration_p4' => '<a href="https://libguides.thedtl.org/home" target="blank">Digital Theological Library</a>',
    'digital_collaboration_p5' => '<a href="https://libguides.thedtl.org/oadtl" target="blank">Open Access Digital Theological Library</a>',
    'digital_collaboration_p6' => '<a href="https://drive.google.com/file/d/1PnlrHZex8IZ0HkEmXWMBu65o7LxgzAby/view" target="blank">Curriculum</a>',
    'digital_collaboration_p7' => '<a href="https://drive.google.com/file/d/1JrkCM4pe4SGFpg7jnbqIrn50uuenv3QC/view" target="blank">The Hispanic/Latina Church in the United States</a>',
    'digital_collaboration_p8' => '<a href="https://drive.google.com/file/d/17-I7IYvIcxAvv3AeJHrmxBenql7F9GcW/view" target="blank">Various Topics</a>',

    'virtual_bookstore' => 'AETH Virtual Bookstore',
    'virtual_bookstore_desc' => 'The AETH bookstore offers resources for Hispanic theological education and leadership.',

    'collab_1' => 'Collaborate | Contribute | Connect',
    'collab_2' => 'VIRTUAL LIBRARY ReDET',
    'community_desc1' => 'ReDET creates common projects for the enrichment of all our institutions. This type of collaboration makes possible what we cannot do alone but can achieve together. There are many possibilities ahead of us as ReDET, and together we dream of new things that will make us excellent and effective theological educators, whether in an institute, church, center, seminary, college, or university.',
    'community_desc2' => 'Our first project is an interactive online subscription platform, ReDET, which will include an open-source system in organizational development documents (i.e., strategic planning, operations, and finance). This project was accomplished with the participation and collaboration of ReDET members who also participate in communities of practice. The need for strategic documents is valuable to our institutions, as listed within the institutional standards of AETH:',
    'community_desc3' => 'Institutes will develop and make available, in writing, bylaws/regulations and comparable documents that define levels of institutional responsibility, as well as legal documents and authorization from applicable church, governmental, and educational accrediting bodies. These documents must be periodically reviewed to verify compliance. (AETH Certification Manual, p. 9).',
    'community_desc4' => 'The general purpose of this project is to build the means (vehicles) and collaborative capacity among Hispanic Biblical Institutes and similar training programs for Hispanic church leaders by creating a collaboration network that can work to solve common problems, innovate, and work on joint projects that will improve the quality of their operations and elevate enrollment and graduation levels.',
    'clickaccess' => 'Click here to access ReDET resources',
    'member_p1' => 'How to become a member of ReDET?',
    'member_p2' => 'In April 2017, the extraordinary Assembly of AETH unanimously ratified the need to form ReDET and established it as one of its strategic priorities. With the creation of ReDET, AETH has taken the initiative to facilitate encounters, synergy, and collaboration among individuals and entities dedicated to Hispanic theological education interested in jointly seeking solutions to common problems, overcoming shared barriers, and identifying the particular contributions each is making.',
    'member_p3' => 'Individual or institutional members of AETH can expand their benefits and potential to transform theological education by also becoming members of ReDET. To do this, they must fill out the corresponding form—either for individuals or organizations—found on this webpage. They will receive a response to their application once ReDET verifies that they meet the requirements. In the response, they will find instructions to activate their membership.',
    'faq_q1' => 'Individual Membership of ReDET',
    'faq_a1' => '<p>AETH recognizes that among its members are individuals eager to identify the particular contributions each is making and committed to jointly seeking solutions to common problems and barriers in Hispanic theological education programs. Therefore, it is important for AETH members to join ReDET if:</p>
<p>They have formal studies in the field of theological education or related fields in the education and administration of educational institutions,</p>
<p>Or they have extensive experience leading educational training programs, both within and outside the theological-pastoral field.</p>
<p>If you are one of these individuals, we invite you to strengthen ReDET with your knowledge and experience.</p>
<p>Your contribution is necessary to transform the situation.</p>
<p><strong>Become a member of ReDET!</strong></p><p><a href="https://aeth.info/afiliacion" target="blank">AETH Membership Page</a>',

    'faq_q2' => 'Institutional Membership of ReDET',
    'faq_a2' => '<p>AETH recognizes that among its members are individuals eager to identify the particular contributions each is making and committed to jointly seeking solutions to common problems and barriers in Hispanic theological education programs. Therefore, it is important for AETH members to join ReDET if:</p>
<p>They have formal studies in the field of theological education or related fields in the education and administration of educational institutions,</p>
<p>Or they have extensive experience leading educational training programs, both within and outside the theological-pastoral field.</p>
<p>If you are one of these individuals, we invite you to strengthen ReDET with your knowledge and experience.</p>
<p>Your contribution is necessary to transform the situation.</p>
<p><strong>Become a member of ReDET!</strong></p><p><a href="https://aeth.info/afiliacion" target="blank">AETH Membership Page</a>',

);
