<?php // lang_es.php
$lang = array(
    'home' => 'Home',
    'about' => 'Sobre Nosotros',
    'contact' => 'Contacto',
    'website_name' => 'COLAB Enriqueciendo a todas nuestras instituciones',
    'somosredet' => '#somosREDET',
    'colab' => 'CoLAB',
    'comunidad' => 'Comunidad de Práctica',
    'members' => 'Membresia',
    'news' => 'News',
    'membresias' => 'Membresías',
    'saber_mas' => 'Saber Más',
    'ser_miembro' => 'Ser Miembro',
    'ser_miembro_desc1' => 'Todos los miembros individuales e institucionales de AETH, interesados en la educación teológica hispana / latina (a), pueden ser miembros de ReDET. Cuentan con las siguientes categorías de miembros:',
    'ser_miembro_desc2' => '<b>Membresía de Personas:</b> Para mujeres y hombres que sirven como educadores en educación teológica; estudiantes matriculados en cualquier institución de educación teológica de pregrado, instituto bíblico o programa de capacitación ministerial; pastores o líderes de denominaciones e iglesias, o trabajadores de organizaciones religiosas o no gubernamentales, y otros interesados en la educación teológica.',
    'ser_miembro_desc3' => '<b>Membresía de Organizaciones:</b> Para Seminarios, Facultades de teología, Institutos bíblicos, empresas de servicio u organizaciones basadas en la fe.',
    'redet_name' => 'Red de Entidades Teológicas (ReDET)',
    'redet_desc1' => 'Expandiendo conexiones a través de la Educación teológica.',
    'redt_desc2' => '<b>ReDET</b> es una comunidad de personas y entidades creada para el apoyo mutuo, la colaboración y la solución de problemas comunes en la educación teológica.',
    'association' => 'Asociación para la Educación Teológica Hispana.',
    'lilly' => 'Lilly Endowment is a private foundation since 1937',
    'description' => 'REDET es una red dedicada a avanzar la educación teológica en toda América Latina. Proporciona recursos, oportunidades de colaboración y formación para apoyar a las instituciones en su misión de desarrollar líderes cristianos. Al fomentar asociaciones entre escuelas teológicas y promover la educación de calidad, REDET busca empoderar comunidades, mejorar el desarrollo del liderazgo y fortalecer el impacto del ministerio cristiano en la región.',
    'visit' => 'visitar',
    'nosotros' => 'NOSOTROS',
    'about_desc1' => 'Somos ReDET, personas y entidades dedicadas a la formación teológica de líderes para el servicio a las comunidades hispanas y latinas que, como un solo cuerpo, conformamos un movimiento de colaboración en el que:',
    'about_desc2' => '1. Compartimos nuestra experiencia y conocimiento para identificar necesidades y oportunidades comunes, y para aprender unos de otros.',
    'about_desc3' => '2. Buscamos resolver en conjunto problemas y superar barreras que tenemos en común.',
    'about_desc4' => '3. Creamos e imaginamos oportunidades para expandir el alcance y para elevar la calidad de nuestros ministerios. ',
    'about_desc5' => '4. Procuramos desarrollar las condiciones, que por separado son difíciles de alcanzar, para que nuestro trabajo y nuestra enseñanza sean más relevantes a las comunidades a que servimos.',
    'about_desc6' => '5. Visionamos e innovamos alternativas metodológicas y organizacionales para que nuestras instituciones y organizaciones sean canales de servicio y señales del Reino de Dios.',
    'about_mission' => 'Fomentar la colaboración entre líderes de institutos bíblicos hispanos y de otros programas de formación teológica para resolver juntos problemas comunes y aprovechar las oportunidades que permitan cambios que resulten en el aumento de estudiantes y de personas graduadas capaces de servir a la iglesia y a la sociedad de una manera relevante.',
    'about_vision' => 'Constituir un movimiento de personas y entidades comprometido con la mejora constante y contextual de programas de educación teológica hispana para que nuestras iglesias y organizaciones sean canales de servicio y señales del Reino de Dios en el mundo.',
    'vision' => 'Vision',
    'mission' => 'Mission',
    'elearning' => 'e-learning',
    'elearning_desc' => 'Proporciona métodos de instrucción y presentaciones de video interactivas (módulos de e-Learning), que se centran en las herramientas que se encuentran en coLAB.',
    'elearning_page_p1' => 'Recurso',
    'elearning_page_p2' => 'Los primeros módulos de e-Learning de ReDET están dedicados a la planificación estratégica, para Institutos Bíblicos (IB), buscando un mayor estándar de excelencia dentro de la estructura y el contenido. Los módulos están en español con subtítulos en inglés y cada video tendrá una duración de 15 minutos a 30 minutos.',
    'elearning_page_p3' => '<b>Módulo uno de e-Learning:</b> Desarrollo de la declaración de misión, visión y valores (historia)',
    'elearning_page_p4' => '<b>Módulo de aprendizaje electrónico dos:</b> Identificación de problemas y objetivos estratégicos',
    'elearning_page_p5' => '<b>Módulo de e-Learning tres:</b> Recursos humanos',
    'elearning_page_p6' => '<b>Módulo de e-Learning cuatro:</b> Presupuesto operativo',
    'elearning_page_p7' => '<b>Módulo cinco de e-Learning:</b> Contratación y marketing [mercadeo]',
    'elearning_page_p8' => '<b>Módulo seis de e-Learning:</b> Supervise y evalúe su plan estratégico | Evalúe sus prácticas de planificación estratégica',
    'elearning_page_p9' => 'Consultar recursos',

    'plan' => 'Plan Estratégico',
    'plan_desc' => 'Muestras de planes estratégicos y artículos valiosos sobre el tema.',
    'plan_page1' => 'Este catálogo contiene muestras de planes estratégicos de organizaciones miembros de ReDET. Además, encontrará artículos valiosos sobre el tema escritos por  otras organizaciones.',
    'plan_page2' => '<a href="https://www.wartburgseminary.edu/download/strategic-plan-2017-2020/" target="blank">Wartburg Seminary</a>',
    'plan_page3' => '<a href="https://alban.org/category/strategic-planning/" target="blank">Alban Institute at Duke Divinity School</a>',
    'plan_page4' => '<a href="https://drive.google.com/drive/folders/14A8XSAXrDGAvplUYBYeuz9GHNHj5408p" target="blank">ReDET</a>',
    'recurso' => 'Recurso',
    'liderasgo' => 'Liderazgo',
    'liderasgo_desc' => 'Artículos valiosos sobre el tema del liderazgo en una variedad de contextos escritos por diversos autores y organizaciones.',
    'liderazgo_page1' => 'Este catálogo contiene artículos valiosos sobre el tema del liderazgo en una variedad de contextos escritos por diversos autores y organizaciones',
    'liderazgo_page2' => '<a href="https://alban.org/category/leadership/page/2/" target="blank">Alban Institute at Duke Divinity School</a>',
    'liderazgo_page3' => '<a href=" https://drive.google.com/file/d/1gVWuCEn8BFPPTfvVk0rcsMjLvDFwyVKO/view" target="blank"> Catálogo Institucional IBIT</a>',

    'formation' => 'Formácion Espiritual',
    'formation_desc' => 'Sitios web de organizaciones dedicadas a la formación espiritual en una variedad de entornos y al servicio de diferentes comunidades.',
    'formation_p1' => 'Este catálogo contiene los sitios web de organizaciones dedicadas a la formación espiritual en una variedad de entornos y al servicio de diferentes comunidades.',
    'formation_p2' => '<a href="https://www.redet.us/www.ashreimexico.net" target="blank">Ashrei Spiritual Formation </a>',
    'formation_p3' => '<a href="https://renovare.org/" target="blank">Renovaré </a>',
    'formation_p4' => '<a href="https://thecrucibleproject.org/" target="blank">The Crucible Project (Men/Women Retreats) </a>',
    'formation_p5' => '<a href="http://daretosoarcouples.com/" target="blank">Dare to Soar (Couples) </a>',



    'segunda' => 'Segunda Generácion',
    'segunda_desc' => 'Recursos que abordan hispanos / latinos de segunda generación.',
    'segunda_p1' => 'Este catálogo contiene podcasts dirigidos a personas mixtas hispanas / latinas y a la iglesia mixta. Los podcasts responden preguntas sobre los desafíos de la primera, segunda y tercera generación de inmigrantes, siendo parte, sirviendo y creciendo en una iglesia étnica.',
    'segunda_p2' => 'The Mestizo Podcast por World Outspoken.',
    'segunda_p3' => 'Podcasts dirigidos a personas mixtas hispanas / latinas, a la iglesia mixta, y generación de inmigrantes, siendo parte, sirviendo y creciendo en una iglesia étnica.Cada uno de los episodios es publicado cada miércoles (para un total de 8 episodios).Miembros de AETH pueden suscribirse a los podcasts en cualquier plataforma (Apple Podcast, Spotify, Google Podcast, y Stitcher) para que no se pierdan los episodios.',

    'newcatalog' => 'Catálogo de Instituto Bíblico',
    'newcatalog_desc' => 'Muestras de planes estratégicos y artículos valiosos sobre el tema',
    'catalogo_p1' => 'Este catálogo contiene muestras de catálogos de institutos bíblicos miembros de ReDET.',
    'catalogo_p2' => '<a href="http://ibitibi.org/wp-content/uploads/2019/07/Catalogo-de-IBIT-2019-2020.docx" target="blank">El Instituto Bíblico Internacional de Texas </a>',

    'materiales' => 'Materiales Didáticos',
    'materiales_desc' => 'Sitios web y otras fuentes que ofrecen información útil, artículos, libros y otros materiales para la instrucción.',
    'materiales_p1' => 'Este catálogo contiene sitios web y otras fuentes que ofrecen información útil, artículos, libros y otros materiales para la instrucción.',
    'materiales_p2' => '<a href="https://www.tallerteologicolatinoamericano.org/" target="blank">Taller Teológico Latinoamericano</a>',
    'materiales_p3' => '<a href="https://bibleproject.com/" target="blank">Bible Project</a>',
    'materiales_p4' => '<a href="https://www.tallerteologicolatinoamericano.org/" target="blank">Taller Teológico Latinoamericano</a>',
    'materiales_p5' => '<a href="https://ibitibi.org/en/start-home-page" target="blank">Instituto Bíbico Internacional de Texas</a>',
    'materiales_p6' => '<a href="https://redinbi.org/" target="blank">Graduate School of Theology</a>',

    'materiales_inter' => 'Materiales Interculturales',
    'materiales_inter_desc' => 'Sitios web y otras fuentes con enfoque intercultural.',
    'materialesinter_p1' => 'Este catálogo contiene sitios web y otras fuentes con enfoque intercultural.',
    'materialesinter_p2' => '<a href="http://www.missiology.org/" target="blank">Missiology</a>',
    'materialesinter_p3' => '<a href="https://missionalive.org/" target="blank">Mission Alive</a>',

    'desarollo' => 'Desarollo Organizacional',
    'desarollo_desc' => 'Sitios web y artículos sobre análisis PESTEL.',
    'desarollo_p1' => 'Este catálogo contiene sitios web y artículos sobre análisis PESTEL: variables políticas, económicas, sociales, tecnológicas, ecológicas y legales que afectan al objeto de estudio desde su entorno más lejano. ',
    'desarollo_p2' => '<a href="http://www.ncd-international.org/" target="blank">National Church Development (NCD)</a>',
    'desarollo_p3' => '<a href="https://www.thebowencenter.org/introduction-eight-concepts" target="blank">The Bowen Center for the study of the Family</a>',


    'sistema' => 'Sistema de Manejo de Aprendizaje',
    'sistema_desc' => 'Sitios web e información sobre sistemas de manejo del aprendizaje virtual.',
    'sistema_p1' => 'Este catálogo contiene sitios web e información sobre sistemas de manejo del aprendizaje virtual.',
    'sistema_p2' => '<a href="https://www.d2l.com/products/learning-environment/" target="blank">D2L – Desire to Learn: Brightspace Learning Environment</a>',
    'sistema_p3' => '<a href="https://360.articulate.com/" target="blank">Articulate</a>',
    'sistema_p4' => '<a href="https://moodle.com/" target="blank">Moodle</a>',
    'sistema_p5' => '<a href="https://www.instructure.com/canvas" target="blank">Canvas</a>',
    'sistema_p6' => '<a href="https://www.blackboard.com/" target="blank">Blackboard</a>',

    'colaboracion' => 'Coláboracion digital de biblioteca',
    'colaboracion_desc' => 'Sitios web e información sobre plataformas digitales para el intercambio de recursos y de colaboración interbibliotecaria.',
    'colaboracion_p1' => 'Este catálogo contiene sitios web e información sobre plataformas digitales para el intercambio de recursos y de colaboración interbibliotecaria. (Su institución debe tener autorización previa para utilizar estas aplicaciones)',
    'colaboracion_p2' => '<a href="https://www.atla.com/" target="blank">American Theological Library Association</a>',
    'colaboracion_p3' => '<a href="https://www.digitaliapublishing.com/" target="blank">Digitalia Hispánica</a>',
    'colaboracion_p4' => '<a href="https://libguides.thedtl.org/home" target="blank">Digital Theological Library</a>',
    'colaboracion_p5' => '<a href="https://libguides.thedtl.org/oadtl" target="blank">Open Access Digital Theological Library</a>',
    'colaboracion_p6' => '<a href="https://drive.google.com/file/d/1PnlrHZex8IZ0HkEmXWMBu65o7LxgzAby/view" target="blank">Currículo</a>',
    'colaboracion_p7' => '<a href="https://drive.google.com/file/d/1JrkCM4pe4SGFpg7jnbqIrn50uuenv3QC/view" target="blank">La Iglesia Hispana/Latina en los Estados Unidos</a>',
    'colaboracion_p8' => '<a href="https://drive.google.com/file/d/17-I7IYvIcxAvv3AeJHrmxBenql7F9GcW/view" target="blank">Tópicos Variados</a>',

    'libreria' => 'Librería Virtual AETH',
    'libreria_desc' => 'The AETH bookstore offers resources for Hispanic theological education and leadership.',


    'colab_1' => 'Colaborar | Contribuir | Conectar',
    'colab_2' => 'BIBLIOTECA VIRTUAL ReDET',
    'comunidad_desc1' => 'ReDET crea proyectos comunes para el enriquecimiento de todas nuestras instituciones. Este tipo de colaboración hace posible lo que solos no podemos hacer pero entre todos podemos lograr. Hay muchas posibilidades delante de nosotros como ReDET y juntos soñamos con las nuevas cosas que nos harán excelentes y efectivos educadores teológicos ya sea en un instituto, la iglesia, un centro, seminario, colegio o universidad.',
    'comunidad_desc2' => 'Nuestro primer proyecto es una plataforma digital interactiva de suscripción en línea ReDET que incluirá un sistema de código abierto en documentos de desarrollo organizacional (es decir, planificación estratégica, operaciones y finanzas). Este proyecto se cumplio con la participación y colaboración de miembros de ReDET que también participan en las comunidades de práctica.Las necesidades de tener documentos estratégicos son valiosas para nuestras instituciones, como se enumera dentro de los estándares institucionales de AETH:',
    'comunidad_desc3' => 'Los institutos desarrollarán y pondrán a disposición, por escrito, estatutos / reglamentos y los documentos comparables que definan los niveles de responsabilidad institucional, así como los documentos legales y la autorización de los organismos de acreditación eclesiales, gubernamentales y educativos aplicables. Estos documentos deben revisarse periódicamente para verificar su cumplimiento. (Manual de certificación de AETH, pág. 9).',
    'comunidad_desc4' => 'El propósito general de este proyecto es el de construir los medios (vehículos) y la capacidad de colaboración entre los Institutos Bíblicos Hispanos, y programas similares de capacitación teológica de líderes de iglesias hispanas mediante la creación de una red de colaboración que pueda trabajar para resolver problemas comunes, la innovación. y trabajar en proyectos conjuntos que mejorarán la calidad de su funcionamiento y elevarán los niveles de matrícula y graduados.',
    'clickaccess' => 'Haga clic aquí para acceder a los recursos de ReDET',
    'member_p1' => '¿Cómo hacerse miembro de ReDET?',
    'member_p2' => 'En abril del 2017, la Asamblea extraordinaria de AETH ratificó de manera unánime la necesidad de formar la ReDET y la estableció como una de sus prioridades estratégicas. Con la creación de la ReDET, AETH ha tomado la iniciativa de facili- tar el encuentro, la sinergia y la colaboración entre personas y entidades dedicadas a la educación teológica hispana inte- resadas en la búsqueda conjunta de soluciones a problemas comunes, en la superación de barreras que comparten y en identificar las contribuciones particulares que cada uno está haciendo.',
    'member_p3' => 'Miembros individuales o institucionales de AETH pueden ampliar sus beneficios y su potencial para transformar la educa- ción teológica, haciéndose también miembros de ReDET. Para esto deben llenar el formulario correspondiente – para per- sona o para organización – que se encuentra en esta página web. Recibirán una respuesta a su solicitud, una vez ReDET corrobore que cumplen con los requisitos. En la respuesta encontrarán las indicaciones para activar su membresía.',
    'faq_q1' => 'Membresía individual de ReDET',
    'faq_a1' => '<p>AETH reconoce que dentro de sus miembros hay personas deseosas de identificar las contribuciones particulares que cada uno está haciendo y comprometidas a buscar de manera conjunta soluciones a problemas y barreras comunes en programas de educación teológica hispana. Por eso es importante que miembros de AETH se unan a ReDET si:</p>
<p>Cuentan con estudios formales en el campo de la educación teológica o en campos relacionados con la educación y la administración de instituciones educativas,</p>
<p>O cuentan con amplia experiencia dirigiendo programas de formación educativa, dentro y fuera del campo teológico-pastoral.</p>
<p>Si tú eres una de estas personas, te invitamos a que con tu conocimiento y experiencia fortalezcas la ReDET.</p>
<p>Tu aporte es necesario para transformar la situación.</p>
<p><strong>¡Hazte miembro de ReDET!</strong></p><p><a href="https://aeth.info/afiliacion" target="blank">Página de membresía de AETH</a>',

    'faq_q2' => 'Membresía institucional de ReDET',
    'faq_a2' => '<p>AETH reconoce que dentro de sus miembros hay personas deseosas de identificar las contribuciones particulares que cada uno está haciendo y comprometidas a buscar de manera conjunta soluciones a problemas y barreras comunes en programas de educación teológica hispana. Por eso es importante que miembros de AETH se unan a ReDET si:</p>
<p>Cuentan con estudios formales en el campo de la educación teológica o en campos relacionados con la educación y la administración de instituciones educativas,</p>
<p>O cuentan con amplia experiencia dirigiendo programas de formación educativa, dentro y fuera del campo teológico-pastoral.</p>
<p>Si tú eres una de estas personas, te invitamos a que con tu conocimiento y experiencia fortalezcas la ReDET.</p>
<p>Tu aporte es necesario para transformar la situación.</p>
<p><strong>¡Hazte miembro de ReDET!</strong></p><p><a href="https://aeth.info/afiliacion" target="blank">Página de membresía de AETH</a>',
);
