<?php // lang_pt.php
$lang = array(
    'title' => 'Bem-vindo',
    'description' => 'L.O.V.E.',
    'home' => 'Início',
    'about' => 'Sobre Nós',
    'pages' => 'Páginas',
    'causes' => 'Causas',
    'blog' => 'Blog',
    'contact' => 'Contato',
    'collection' => 'Coleção',
    'friends' => 'Amigos do Centro',
    'subscription' => 'Assinatura',
    'website_name' => 'Centro de Recursos Justo & Catherine Gonzalez',
    'about_the' => 'Sobre o Centro Gonzalez',
    'mission' => 'Nossa Missão',
    'mission_statement' => 'Promover e apoiar a contribuição Latino para a liderança ministerial através de diálogo, recursos educacionais e pesquisa.',
    'more_about' => 'Mais Sobre Nós',
    'support_hispanic' => 'Apoie a Comunidade Hispânica',
    'goal' => 'Nosso Objetivo',
    'goal_1' => 'Um lugar físico e virtual que:',
    'goal_2' => 'Aumenta a conscientização sobre perspectivas e herança latino-americanas, proporcionando acesso digital aos seus recursos;',
    'goal_3' => 'Explora novas fronteiras na teologia latino-americana e oferece um fórum para aqueles comprometidos com o bem-estar das igrejas e comunidades latinas para Coleçãoexplorar e desenvolver novas visões e práticas.',
    'vision' => 'Nossa Visão',
    'vision1' => 'Um lugar físico e virtual que:',
    'vision2' => 'Aumenta a conscientização sobre perspectivas e herança latino-americanas, proporcionando acesso digital aos seus recursos;',
    'vision3' => 'Explora novas fronteiras na teologia latino-americana e oferece um fórum para aqueles comprometidos com o bem-estar das igrejas e comunidades latinas para explorar e desenvolver novas visões e práticas.',
    'testimonial1' => 'Os escritos de Justo e Catherine Gonzalez ajudaram cristãos ao redor do mundo a entender a história da igreja de novas e mais profundas maneiras. O Centro de Recursos está realizando um trabalho essencial ao tornar esses materiais disponíveis para todos.',
    'testimonial2' => 'O trabalho de Justo Gonzalez é um tesouro, e estou empolgado em saber que será amplamente disponível para a posteridade através do Centro de Recursos Justo e Catherine Gonzalez.',
    'testimonial3' => 'A amplitude de seu trabalho em história, teologia e formação ministerial torna o Centro de Recursos Gonzalez um local indispensável para pesquisa arquivística e conversa dinâmica sobre muitas das questões teológicas mais urgentes de nosso tempo.',
    'testimonial4' => 'Ao abraçar seu legado, fomentamos um cenário teológico mais inclusivo, ecumênico e vibrante, onde pontes são construídas entre a academia, seminários e a comunidade eclesiástica mais ampla.',
    'testimonial5' => 'Quando olho para o último século de educação teológica e liderança pastoral nos Estados Unidos e ao redor do mundo, não consigo pensar em duas pessoas mais influentes do que Justo e Catherine Gonzalez.',
    'testimonial6' => 'Através do Centro Justo e Catherine Gonzalez, eles continuarão a inspirar, desafiar e encorajar as futuras gerações a abraçar, apreciar e celebrar o contínuo trabalho da graça abundante de Deus.',
    'email_address' => 'Endereço de E-mail',
    'our_location' => 'Nossa Localização',
    'fell_free' => 'Sinta-se à vontade para nos contatar',
    'justo_influence' => 'A influência do Dr. Justo L. Gonzalez na teologia hispânica é profunda, pois ele tem sido uma figura chave na elevação das vozes e perspectivas dos cristãos hispânicos no discurso teológico. Através de seus escritos e ensinamentos, ele abordou questões de identidade cultural, justiça social e a relevância dos textos bíblicos nas experiências das comunidades latinas. Seu trabalho promove uma compreensão mais profunda da interseção entre fé e cultura, promovendo um cenário teológico mais inclusivo que honra a rica diversidade dentro do cristianismo. Ao orientar jovens teólogos, Gonzalez continua a inspirar a próxima geração a explorar e articular suas próprias percepções teológicas, enriquecendo ainda mais o campo da teologia hispânica.',
    'justo_legacy' => 'Legado de Gonzalez',
    'justo_legacy_1' => 'Dr. Justo L. Gonzalez é um teólogo, historiador e educador distinto, particularmente conhecido por suas contribuições à teologia hispânica. Nascido e criado em Havana, Cuba, Gonzalez foi ordenado ministro na igreja metodista em 1957. Ele então obteve seu Ph.D. em Teologia Histórica pela Universidade de Yale em 1961, tornando-se a pessoa mais jovem a fazê-lo na época.',
    'justo_legacy_2' => 'Ao longo de sua carreira, Gonzalez ensinou em várias instituições teológicas, incluindo o Seminário Evangélico de Porto Rico e a Escola de Teologia Candler na Universidade Emory. Ele escreveu mais de 150 livros, com obras notáveis como "Uma História do Pensamento Cristão" e "A História do Cristianismo", que foram traduzidos para várias línguas.',
    'justo_legacy_3' => 'O Dr. Gonzalez tem sido fundamental para o avanço da educação teológica hispânica. Ele ajudou a fundar a Iniciativa Teológica Hispânica, o Programa de Verão Hispânico e a Associação para a Educação Teológica Hispânica (AETH). Seu compromisso com a educação se reflete ainda mais no Centro de Recursos Justo e Catherine Gonzalez, estabelecido em 2011 para apoiar ministérios latinos.',
    'justo_legacy_4' => 'Mesmo após se aposentar do ensino em tempo integral, Gonzalez continua a escrever, palestrar e orientar jovens teólogos. Ele recebeu várias honrarias, incluindo quatro doutorados honorários e a Medalha de Serviço Distinto da Associação de Escolas Teológicas.',
    'justo_legacy_5' => 'O trabalho de Gonzalez moldou significativamente a hermenêutica bíblica e a teologia construtiva latino-americana, advogando pelo reconhecimento da natureza contextual da teologia e seu enriquecimento através de perspectivas culturais diversas.',
    'degrees' => array(
        'bachelor_of_arts' => '<strong>Bacharelado em Artes (B.A.):</strong> Obteve seu diploma de graduação em teologia na Universidade de Havana em Cuba.',
        'bachelor_of_divinity' => '<strong>Bacharelado em Divindade (B.D.):</strong> Gonzalez obteve seu B.D. no Seminário Teológico Union em Nova York.',
        'phd_historical_theology' => '<strong>Ph.D. em Teologia Histórica:</strong> Obteve seu Ph.D. na Universidade de Yale em 1970, tornando-se a pessoa mais jovem a fazê-lo na época.',
        'doctor_of_ministry' => '<strong>Doctor of Ministry (D.Min.):</strong> Também possui um Doctor of Ministry, enfatizando a aplicação prática da teologia em contextos ministeriais.',
        'honorary_doctorates' => '<strong>Doutorados Honorários:</strong> O Dr. Gonzalez recebeu vários doutorados honorários de várias instituições em reconhecimento às suas contribuições para a teologia e educação, embora as instituições e graus específicos variem.',
    ),
    'achievements' => array(
        'first_latino_phd' => '<strong>Primeiro Latino a Obter um Ph.D. na Universidade de Yale:</strong> O Dr. Gonzalez tornou-se a pessoa mais jovem e o primeiro latino a se formar com um Ph.D. em Teologia Histórica em Yale em 1970.',
        'ordained_minister' => '<strong>Ministro Ordenado:</strong> Foi ordenado ministro na Igreja Metodista em 1957, começando seu longo compromisso com o ministério e a educação teológica.',
        'prolific_author' => '<strong>Autor Prolífico:</strong> O Dr. Gonzalez escreveu mais de 150 livros sobre teologia, história e ministério, contribuindo significativamente para os campos da teologia hispânica e latino-americana.',
        'advocate_hispanic_education' => '<strong>Defensor da Educação Teológica Hispânica:</strong> Ele tem sido fundamental na promoção e desenvolvimento da educação teológica para comunidades hispânicas, ajudando a estabelecer programas que abordam seus contextos culturais únicos.',
        'educator_renowned_institutions' => '<strong>Educador em Instituições Renomadas:</strong> O Dr. Gonzalez ensinou em várias instituições teológicas prestigiadas, incluindo a Escola de Teologia Candler na Universidade Emory e o Centro Teológico Interdenominacional em Atlanta.',
        'international_speaker' => '<strong>Palestrante e Conferencista Internacional:</strong> O Dr. Gonzalez deu palestras em todo o mundo, compartilhando seus insights sobre teologia hispânica, história da igreja e a interseção de fé e cultura.',
        'member_american_academy' => '<strong>Membro da Academia Americana de Artes e Ciências:</strong> Suas contribuições acadêmicas lhe garantiram um lugar nesta prestigiosa organização, reconhecendo sua influência nas humanidades.',
        'founder_hispanic_initiative' => '<strong>Fundador da Iniciativa Teológica Hispânica:</strong> Co-fundou essa iniciativa para aprimorar o treinamento e o apoio para acadêmicos hispânicos na educação teológica.',
    ),
    'video' => 'Vídeos Gonzalez',
    'gallery' => 'Galeria',
    'Advanced_Search' => 'Busca Avançada',
    'Faceted_Search' => 'Busca Facetada',
    'User_Friendly_Interface' => 'Interface Amigável',
    'Rich_Metadata_Integration' => 'Integração de Metadados Ricos',
    'discovery' => 'Descubra o Magnífico Acervo',
    'discovery_description1' => 'Nossa plataforma orgulha-se de exibir o magnífico conteúdo do acervo de Justo e Catherine Gonzalez, oferecendo uma riqueza incomparável de informações e recursos para pesquisa e exploração aprofundadas. Esta coleção exclusiva é um verdadeiro tesouro de insights valiosos e dados históricos, meticulosamente curada para o pesquisador exigente.',
    'discovery2' => 'Desbloqueie o Acesso Premium',
    'discovery_description2' => 'Para manter os mais altos padrões de privacidade e integridade, o acesso a este conteúdo extraordinário está disponível através de um login seguro. Não perca a oportunidade de mergulhar nesta coleção excepcional—entre em contato conosco para obter suas credenciais de acesso e explorar a riqueza do nosso acervo.',
    'youtube_title' => 'Bem-vindo ao Canal de Vídeos Gonzalez',
    'youtube_description' => 'Mergulhe no mundo exclusivo de Justo e Catherine Gonzalez com nosso canal do YouTube, sua porta de entrada para uma rica coleção de conteúdos selecionados. Nosso canal oferece uma variedade de vídeos únicos e insights que não estão disponíveis em outros lugares.',
    'Exclusive_Content' => 'Conteúdo Exclusivo',
    'youtube_description2' => 'Desfrute de acesso a uma gama de vídeos exclusivos, incluindo explorações detalhadas, entrevistas e conteúdo de bastidores relacionado a Justo e Catherine Gonzalez. Descubra materiais raros e exclusivos que fornecem uma compreensão mais profunda de seu trabalho e legado.',
    'friend_of_the_center_title' => 'Torne-se um Amigo do Centro',
    'friend_of_the_center_description' => 'Junte-se a nós para sustentar o valioso trabalho do Centro de Recursos Justo Gonzalez tornando-se um “Amigo do Centro.” Seu apoio é crucial para manter e aprimorar os recursos e programas do nosso centro.',
    'Friends' => 'Amigos',
    'why_become' => 'Por Que Se Tornar um Amigo do Centro?',
    'sustain_services' => '<strong>Sustente Serviços Essenciais:</strong> Sua doação mensal ou anual ajuda a garantir que nosso centro continue a fornecer serviços e recursos essenciais para aqueles que precisam.',
    'preserve_resources' => '<strong>Preserve Recursos Valiosos:</strong> As contribuições nos ajudam a manter e expandir nossa coleção, permitindo-nos oferecer mais materiais e oportunidades valiosas para pesquisa e educação.',
    'make_impact' => '<strong>Faça um Impacto Duradouro:</strong> Ao se juntar ao programa “Amigo do Centro”, você desempenha um papel vital na preservação e promoção do legado de Justo Gonzalez, garantindo que as futuras gerações possam continuar a acessar e aprender com este recurso inestimável.',
    'benefits' => 'Benefícios de Participar',
    'exclusive_updates' => '<stronAtualizações Exclusivas: Receba atualizações regulares sobre as atividades do centro, novas aquisições e eventos especiais.',
    'recognition' => 'Reconhecimento: Como um sinal de nossa gratidão, você será reconhecido por seu apoio generoso em nossas publicações e em nosso site.',
    'special_access' => 'Acesso Especial: Desfrute de acesso exclusivo a eventos especiais e prévias de novos recursos e coleções.',
    'how_to_get_involved' => 'Como Se Envolver',
    'simple_process' => 'Tornar-se um “Amigo do Centro” é simples. Escolha um plano de doação mensal ou anual que se encaixe no seu orçamento e faça a diferença na sustentabilidade do Centro de Recursos Justo Gonzalez.',
    'support_mission' => 'Apoie nossa missão, preserve nosso patrimônio e faça parte de algo significativo. Junte-se a nós hoje e ajude-nos a continuar nosso trabalho importante!',
    'join_us' => 'Junte-se a Nós',
    'catherine_gonzalez_profile' => 'Catherine Gonzalez fez contribuições significativas no campo da teologia e no estudo das tradições religiosas hispânicas. Como acadêmica e educadora proeminente, seu trabalho tem sido fundamental para avançar a compreensão dos problemas teológicos dentro das comunidades latinas. Através de sua pesquisa, escritos e ensinamentos, Gonzalez abordou temas como a interseção de gênero, cultura e fé, e destacou o papel das mulheres na formação do discurso teológico.',
    'catherine_gonzalez_contributions' => 'O trabalho acadêmico de Gonzalez tem sido crucial para explorar como as perspectivas culturais e de gênero influenciam o pensamento e a prática teológica. Seu compromisso em promover um ambiente teológico mais inclusivo e diversificado ajudou a elevar as vozes de grupos marginalizados dentro do cristianismo. Ao focar nas experiências e contribuições das mulheres hispânicas na teologia, ela ampliou a narrativa e enriqueceu o diálogo acadêmico sobre esses temas cruciais.',
    'catherine_gonzalez_impact' => 'Através de seus esforços educacionais e de mentoria, Catherine Gonzalez continua a inspirar e apoiar a próxima geração de teólogos, incentivando-os a se envolver e contribuir para a rica tapeçaria da teologia hispânica. Sua dedicação em expandir as perspectivas teológicas e promover a justiça social teve um impacto duradouro tanto na comunidade acadêmica quanto na igreja em geral.',
    'catherine_gonzalez_achievements' => array(
        'pioneering_research' => '<strong>Pesquisa Pioneira em Teologia Hispânica:</strong> Gonzalez realizou pesquisas inovadoras explorando as interseções entre gênero, cultura e fé no contexto das tradições religiosas hispânicas. Seu trabalho foi fundamental para avançar a compreensão dessas questões e seu impacto no discurso teológico.',
        'influential_publications' => '<strong>Publicações Influentes:</strong> Ela escreveu várias obras significativas que contribuíram para a comunidade acadêmica e teológica. Suas publicações frequentemente abordam identidade cultural e o papel das mulheres na teologia, proporcionando perspectivas valiosas e promovendo uma compreensão mais profunda desses temas importantes.',
        'advancing_gender_inclusivity' => '<strong>Avanço na Inclusividade de Gênero:</strong> Gonzalez tem sido uma defensora proeminente da inclusão das vozes e perspectivas femininas nos estudos teológicos. Seus esforços ajudaram a destacar e abordar as disparidades de gênero no campo, promovendo um ambiente acadêmico mais inclusivo e equitativo.',
        'educational_leadership' => '<strong>Liderança Educacional:</strong> Como educadora, Gonzalez desempenhou um papel crucial na orientação e formação da próxima geração de teólogos. Seu ensino e orientação influenciaram as carreiras de muitos acadêmicos, ajudando-os a navegar e contribuir para o campo em evolução da teologia.',
        'promotion_of_social_justice' => '<strong>Promoção da Justiça Social:</strong> Seu trabalho vai além da pesquisa acadêmica para se envolver ativamente com questões de justiça social. Gonzalez usou sua plataforma para advogar por comunidades marginalizadas e abordar injustiças sistêmicas dentro das instituições religiosas e acadêmicas.',
        'collaborative_projects' => '<strong>Projetos Colaborativos e Conferências:</strong> Gonzalez participou e organizou várias conferências acadêmicas e projetos colaborativos que reúnem acadêmicos de diversos contextos para discutir e desenvolver novas perspectivas teológicas. Essas iniciativas promoveram um maior diálogo e compreensão dentro do campo.',
        'recognition_and_honors' => '<strong>Reconhecimento e Honras:</strong> Suas contribuições para a teologia e a educação foram reconhecidas através de diversos prêmios e honras. Esses reconhecimentos refletem seu impacto na comunidade acadêmica e seu compromisso com o avanço do estudo teológico.',
    ),
    'catherine_gonzalez_degrees' => array(
        'bachelor_of_arts' => '<strong>Bacharelado em Artes (B.A.):</strong> Obteve seu diploma de graduação em estudos religiosos na Universidade de Harvard.',
        'master_of_divinity' => '<strong>Mestrado em Divindade (M.Div.):</strong> Completou seu Mestrado em Divindade na Escola de Teologia de Harvard.',
        'doctor_of_philosophy' => '<strong>Doutorado em Filosofia (Ph.D.):</strong> Obteve seu Ph.D. em Teologia na Universidade de Princeton, com uma tese focada na teologia da libertação.',
        'honorary_degrees' => '<strong>Diplomas Honorários:</strong> Recebeu vários diplomas honorários em reconhecimento por suas contribuições à teologia e à educação teológica.',
    ),
    'catherine_gonzalez_honors' => array(
        'prestigious_awards' => '<strong>Prêmios Prestigiados:</strong> Foi agraciada com diversos prêmios em reconhecimento ao seu impacto no campo da teologia e da justiça social.',
        'academic_organizations' => '<strong>Membro de Organizações Acadêmicas:</strong> Foi reconhecida como membro honorário de várias organizações acadêmicas importantes, destacando sua influência no meio acadêmico.',
        'public_recognition' => '<strong>Reconhecimento Público:</strong> Seu trabalho foi destacado em diversas publicações acadêmicas e meios de comunicação, refletindo seu impacto e contribuições para a teologia e a justiça social.',
    ),
    'gonzalez_center_description' => array(
        'legacy_title' => '<strong>Criando um Legado de Excelência Teológica</strong>',
        'legacy_description' => 'O Centro de Recursos Justo e Catherine Gonzalez se destaca como um farol de excelência no estudo teológico latino, forjando um legado profundo no campo da fé e da exploração intelectual. Nomeado em homenagem a Justo e Catherine Gonzalez, o Centro incorpora seu compromisso com o avanço da compreensão teológica e a promoção de um ambiente acadêmico rico para estudiosos e praticantes latinos.',
        'majesty_title' => '<strong>Um Majestoso Repositório de Conhecimento</strong>',
        'majesty_description' => 'No coração do Centro Gonzalez está seu majestoso repositório de recursos, cuidadosamente curado para apoiar e aprimorar o estudo da teologia latina. A extensa coleção do Centro abrange uma ampla gama de temas, incluindo teologia histórica, teologia da libertação e estudos culturais, refletindo a profundidade e diversidade do pensamento latino. Ao fornecer acesso a uma vasta gama de materiais acadêmicos, o Centro permite que pesquisadores, estudantes e teólogos explorem e se envolvam com as perspectivas sutis que moldam as tradições cristãs latinas.',
        'contribution_title' => '<strong>Contribuindo para a Teologia Latina Hoje</strong>',
        'contribution_description' => 'O Centro Gonzalez desempenha um papel fundamental na formação da teologia latina hoje, servindo como um centro central para pesquisa e educação teológica. Através de seus robustos programas e recursos, o Centro promove o desenvolvimento de novas ideias teológicas e incentiva a exploração de questões críticas dentro das comunidades latinas. Suas iniciativas incluem:
            <ul>
                <li><strong>Preservação e Promoção do Patrimônio Teológico Latino:</strong> O Centro protege o rico patrimônio teológico do cristianismo latino, garantindo que obras e contribuições significativas sejam preservadas e acessíveis para as gerações futuras.</li>
                <li><strong>Suporte a Pesquisadores Emergentes:</strong> Ao oferecer suporte à pesquisa, mentoria e oportunidades de desenvolvimento profissional, o Centro fomenta a próxima geração de teólogos e estudiosos latinos, capacitando-os a fazer contribuições significativas no campo.</li>
                <li><strong>Promoção do Diálogo Acadêmico:</strong> O Centro organiza conferências, palestras e workshops que reúnem estudiosos, praticantes e líderes comunitários para participar de diálogos sobre questões teológicas e sociais urgentes, promovendo uma comunidade acadêmica vibrante e colaborativa.</li>
                <li><strong>Ampliação do Acesso Educacional:</strong> Através de seus recursos digitais e programas educacionais, o Centro expande o acesso à educação teológica, possibilitando que um público mais amplo se envolva com o pensamento e a erudição teológica latina.</li>
            </ul>',
    ),

    'gonzalez_center_faq' => array(
        'question_1' => '<strong>O que é o Centro de Recursos Justo e Catherine Gonzalez?</strong>',
        'answer_1' => 'O Centro de Recursos Justo e Catherine Gonzalez é uma instituição dedicada a preservar e promover o legado teológico e acadêmico de Justo e Catherine Gonzalez. Ele fornece acesso a uma vasta coleção de recursos, incluindo livros, artigos e materiais relacionados à teologia hispânica.',

        'question_2' => '<strong>Como posso acessar os recursos do Centro?</strong>',
        'answer_2' => 'Os recursos estão disponíveis online através do nosso site. Para acesso completo a alguns materiais, pode ser necessário credenciais específicas, que podem ser solicitadas entrando em contato com o centro.',

        'question_3' => '<strong>Qual é a missão do Centro de Recursos?</strong>',
        'answer_3' => 'Nossa missão é promover e apoiar a contribuição latina para a formação de líderes ministeriais por meio de diálogo, recursos educacionais e pesquisa, ajudando a expandir a compreensão da teologia hispânica.',

        'question_4' => '<strong>Como posso me tornar um "Amigo do Centro"?</strong>',
        'answer_4' => 'Você pode se tornar um "Amigo do Centro" fazendo uma doação mensal ou anual. Os detalhes para se inscrever e contribuir estão disponíveis na nossa página de "Amigos do Centro" no site.',

        'question_5' => '<strong>Quais são os benefícios de se tornar um "Amigo do Centro"?</strong>',
        'answer_5' => 'Como "Amigo do Centro", você receberá atualizações exclusivas, reconhecimento em nossas publicações e site, e acesso especial a eventos e novos recursos.',

        'question_6' => '<strong>O Centro organiza eventos ou palestras?</strong>',
        'answer_6' => 'Sim, o Centro organiza eventos, palestras e webinars sobre tópicos relevantes para a teologia hispânica e o legado de Justo e Catherine Gonzalez. As datas e detalhes são atualizados regularmente em nosso site.',

        'question_7' => '<strong>Onde posso encontrar os materiais e livros de Justo e Catherine Gonzalez?</strong>',
        'answer_7' => 'Os materiais e livros estão disponíveis em nossa biblioteca online. Para acessar obras específicas, utilize nossa plataforma de pesquisa e catálogos digitais.',

        'question_8' => '<strong>Como posso fazer uma doação ao Centro?</strong>',
        'answer_8' => 'As doações podem ser feitas através do nosso site, onde você encontrará opções para contribuições únicas, mensais ou anuais. As doações ajudam a manter e expandir nossos recursos e programas.',
    ),
    'ceo_description' => array(
        'title' => 'Ondina Gonzalez - Diretora',
        'description' => '<p>Ondina E. González é natural de Cuba, de onde emigrou para os Estados Unidos com sua família quando tinha menos de três anos de idade. Um ano depois, sua família se estabeleceu na cidade de Rome, na Geórgia, onde os pais de Ondina trabalharam no Berry College até sua aposentadoria na década de 90.</p><p>O pai de Ondina, Jorge A. González, era especialista em Antigo Testamento; e sua mãe, Ondina S. González, era muito ativa entre as mulheres metodistas unidas, tanto em nível local quanto nacional. Portanto, não é surpreendente que, em seu lar, houvesse tanto interesse pelo serviço quanto pela educação, e que essas duas paixões tenham guiado a vida de Ondina.</p><p>Após receber simultaneamente um bacharelado em história e um mestrado em história colonial da América Latina, Ondina obteve outro título avançado em finanças internacionais pela American Graduate School of International Management, em Phoenix, Arizona. Retornando à história, ela obteve seu Ph.D. pela Universidade de Emory em 2001.</p><p>Desde então, Ondina lecionou em várias instituições – entre elas, Agnes Scott College e a Universidade de Emory. Mais recentemente, tem se dedicado a servir como Diretora do Centro de Recursos Justo e Catherine González, colaborando neste programa que faz parte da Associação para a Educação Teológica Hispana.</p>',

    ),
    'getaccessdatabase' => 'Acesse agora nossa Coleção Digital!',
    'clickhere' => 'Clique aqui',
    'database_desc1' => '<b>Desbloqueie um mundo de conhecimento e recursos</b> com acesso exclusivo à nossa coleção digital! Se você está pesquisando, aprendendo ou explorando, nossos recursos digitais curados estão aqui para apoiar sua jornada.',
    'database_desc2' => 'Benefícios do Acesso:',
    'database_desc3' => '<b>Arquivos Extensos:</b> Explore uma vasta gama de documentos, publicações e recursos multimídia.',
    'database_desc4' => '<b>Informação Atualizada:</b> Mantenha-se informado com as últimas atualizações e adições à nossa coleção.',
    'database_desc5' => '<b>Interface Amigável:</b> Navegue e pesquise facilmente os materiais que você precisa.',
    'database_desc6' => '<b>Não perca este recurso valioso!</b> Inscreva-se ou Faça login para começar a explorar nossa coleção digital hoje mesmo.',
    'welcome_description' => array(
        'p1' => 'Bem-vindo',
        'p2' => 'Estamos muito felizes que você tenha reservado um tempo para nos visitar.',
        'p3' => 'Aqui você encontrará uma abundância de recursos para apoiá-lo em seu ministério, seus estudos e em sua jornada pessoal de fé.',
        'p4' => 'Talvez o nosso recurso mais acessível seja a coleção digital das obras inéditas do Dr. Justo L. González e daquelas que ele fez com a Dra. Catherine G. González. Esta coleção é um exemplo tangível do importante legado que esses dois grandes líderes da igreja criaram ao longo de mais de 60 anos dedicados à vida da igreja e à educação de seus líderes. Até agora, no entanto, carregamos apenas uma parte dos centenas de documentos mantidos pelo Centro.',
        'p5' => 'Navegue neste site e saiba mais sobre o trabalho que estamos realizando. Leia sobre o Centro como um lugar de encontro, um espaço para sonhar com as inúmeras maneiras pelas quais latinos e latinas podem contribuir para a igreja universal e um lugar onde a história do impacto dos cristãos hispânicos é celebrada e honrada. Saiba sobre o início do Centro como parte da AETH. Conheça aqueles de nós que orientam o trabalho do Centro González e saiba como você também pode apoiar esse trabalho.',
        'p6' => 'O acesso a esses recursos maravilhosos mantidos em nossa coleção é por meio de assinatura, que pode ser adquirida através da AETH ou tornando-se Amigo do Centro (veja abaixo). Role mais para baixo e você encontrará um exemplo de um dos documentos já carregados em nossa coleção.',
        'p7' => 'Este estudo bíblico, publicado em El Discípulo, é um de uma série de treze que abrange um trimestre inteiro de domingos. Já temos várias dessas séries carregadas e disponíveis para aqueles que têm acesso à coleção, e continuaremos a carregar mais no futuro.',
        'p8' => 'Para mais exemplos de alguns de nossos recursos, por favor, visite a página de Coleções neste site clicando aqui.',
        'p9' => 'Para apoiar este importante legado e o trabalho do Centro criado em nome de Justo e Catherine, estabelecemos o programa Amigos do Centro. Este programa é uma via para aqueles que acreditam na necessidade de continuar e expandir o acesso ao trabalho dos González, não apenas através da coleção digital, mas também através das várias outras maneiras pelas quais o Centro apoia e nutre o trabalho dos líderes ministeriais em toda a igreja.',
        'p10' => 'Clique aqui para saber mais sobre o programa e as muitas maneiras pelas quais confiamos nos Amigos para orientar nosso trabalho.',
        'p11' => 'Se você preferir fazer uma doação única em vez de um compromisso contínuo com o nosso trabalho, por favor, clique aqui para ser redirecionado. Saiba que, de qualquer forma que você escolher se tornar parte do importante trabalho que estamos realizando, agradecemos muito sua contribuição e humildemente pedimos suas orações.',
    ),

    'director' => 'Diretora',
    'junior' => array(
        'p1' => 'Wilson Fernandes Junior',
        'p2' => '<p>Conhecido por muitos simplesmente como Junior, brasileiro e compartilha uma jornada de 26 anos com sua esposa, Keyla. Juntos, têm criado seus dois filhos, Daniel (23) e Vitor (21), no norte da Geórgia desde 2018.</p><p>Desenvolvedor full stack por profissão, com um pós-graduação em Análise e Desenvolvimento de Sistemas pela USP no Rio de Janeiro, Brasil, e um diploma em Administração de Sistemas, Junior é dedicado à criação de soluções digitais que atendem às necessidades do mundo dinâmico de hoje. No entanto, seu trabalho vai além do campo da tecnologia; seu propósito mais profundo é servir ao Senhor Jesus Cristo.</p><p>A paixão de Junior pela música se expressa através de seu papel como tecladista e líder de adoração na Igreja Brazil House em Johns Creek, GA. Nessa função, ele lidera outros em adoração, ajudando-os a se tornarem uma parte integral do corpo de Cristo e a seguir a Sua vontade.</p><p>Sua jornada de fé começou aos 12 anos, e desde então, ele tem se dedicado a espalhar a mensagem de amor e esperança. Seus esforços contribuíram para o estabelecimento de igrejas tanto no Brasil quanto nos Estados Unidos.</p><p>Além de seus papéis profissionais e ministeriais, Junior desempenha um papel vital no Centro Justo, onde tem sido fundamental no desenvolvimento de ferramentas e processos para digitalizar os vastos arquivos do centro.</p>',
    ),
    'sophia' => array(
        'p1' => 'Sophia Porter',
        'p2' => '<p>Sophia Porter é estagiária no Centro de Recursos Justo e Catherine González, onde trabalha com o programa Amigo/as do Centro. Ela é estudante atual do curso de Mestrado em Divindade na Candler School of Theology e mora em Atlanta, Geórgia.</p><p> Ela nasceu e foi criada em Marion, Indiana, onde também fez sua graduação. Ela se formou na Indiana Wesleyan University com especializações em Desenvolvimento Comunitário e Ministérios Pastorais.</p><p>Após a graduação, ela estudou linguística espanhola e história na Universidad de Nebrija em Madrid, Espanha.</p><p>Aparte dos estudos, ela adora passar tempo com sua família e amigos próximos. Ela tem aproveitado bastante seu tempo no Centro e espera continuar o trabalho que está sendo realizado.</p>'
    ),
    'jessica' => array(
        'p1' => 'Dr. Jessica Lugo',
        'p2' => '<p>A Revda. Dra. Jessica Lugo Meléndez nasceu em San Juan, PR e cresceu em Deltona, Flórida. Ela é uma ministra ordenada das Igrejas Batista Americanas e faz parte do corpo pastoral das Igrejas Batista de Porto Rico. Ela é professora de História do Cristianismo, Novo Testamento e Evangelismo.</p><p>Com mais de 20 anos de experiência ministerial e secular combinada, a Dra. Lugo escreveu para várias referências teológicas, eclesiásticas e administrativas. Ela possui Doutorado em Ministério pela Liberty University e um MDiv pelo Seminário Evangélico de Porto Rico.</p><p>Em 2024, a Dra. Lugo se tornou a nona Diretora Executiva da Associação para a Educação Teológica Hispana (AETH), supervisionando seus mais de cinco programas, incluindo o Centro de Recursos Justo e Catherine González. Sob sua liderança, a AETH ampliou seus esforços para apoiar e fortalecer a educação teológica para hispânicos.</p>'
    ),
    'donate' => 'Donar Ahora',
    'ourCollection' => 'Nossa Coleção',
    'friends_desc' => array(
    'p1' => 'Se você deseja se envolver mais com o valioso trabalho realizado no Centro de Recursos Justo e Catherine González, considere se tornar um Amigo do Centro. Nossos Amigos são colaboradores vitais para manter e melhorar nossos recursos e programas. Esta parceria é inestimável para nosso trabalho e ajuda a garantir que os recursos do Centro continuem acessíveis ao maior número possível de pessoas.',
    'p2' => 'Os Amigos do Centro são pessoas que apoiam o trabalho e a visão do Centro tanto financeiramente quanto com seus comentários, sugestões e contribuições.',
    'p3' => '<b>Contribuições e sugestões.</b> Como membro deste grupo, suas contribuições e sugestões não só são bem-vindas, mas também solicitadas. Para que seus comentários sejam significativos, você receberá atualizações periódicas sobre as atividades do Centro, bem como acesso à coleção digital do Centro, que geralmente está disponível apenas por assinatura, enquanto permanecer um Amigo. Ao ler sobre o que estamos fazendo ou ao examinar as coleções digitais, esperamos que você nos diga de que forma poderíamos melhorar, quais recursos deveríamos oferecer e nos informe sobre erros que devem ser corrigidos. (Para saber mais sobre a coleção digital, clique aqui.)',
    'p4' => '<b>Comunicação.</b> Como parte do programa Amigos, também enviaremos peças mensais para reflexão. Esses breves ensaios são escritos por pessoas que, como você, estão em uma jornada de fé, já trabalharam ou ainda trabalham em algum tipo de ministério e nos convidam a refletir mais profundamente sobre vários aspectos da fé. Alguns ensaios estarão relacionados ao calendário cristão; no tempo comum, as reflexões geralmente focam em como e onde podemos experimentar Deus de forma mais próxima. Ocasionalmente, recorremos às palavras de pessoas que nos precederam, como Isidoro de Sevilha, para ler pensamentos que inspiraram muitos ao longo dos anos.',
    'p5' => '<b>Apoio financeiro.</b> Indivíduos que fazem uma doação anual de $200,00 ou mais para o Centro terão automaticamente uma assinatura de um ano ao programa de Amigos. Aqueles que fizerem doações mensais recorrentes de $15 ou mais serão Amigos enquanto a contribuição continuar. Se você deseja se tornar um Amigo do Centro, por favor, entre em contato com Luz Ortiz por e-mail em lzortiz@aeth.org ou por telefone no 407-773-1234.',
    'p6' => 'Seu apoio nos ajudará a manter e expandir nossa coleção e nos permitirá oferecer mais materiais valiosos para pesquisa e educação. Portanto, considere fazer um impacto duradouro ao ingressar no programa Amigos do Centro. Você desempenha um papel vital na preservação e promoção do legado de Justo e Catherine González, garantindo que as futuras gerações possam continuar acessando e aprendendo com esses recursos inestimáveis.',
),

'acervo_desc' => array(
    'p1' => 'Você já se perguntou como acessar o trabalho de um dos maiores líderes cristãos contemporâneos da comunidade latina, um de seus mais importantes historiadores e um dos seus mais bem-sucedidos promotores da educação para líderes cristãos hispânicos?',
    'p2' => '<b>Você encontrou o lugar:</b> a coleção digital do Centro de Recursos Justo e Catherine González, um programa da Associação para a Educação Teológica Hispânica. Aqui você encontrará uma variedade de obras não publicadas do Dr. Justo L. González, como sermões, estudos bíblicos e palestras, bem como algumas de suas obras publicadas, incluindo estudos bíblicos em espanhol. Aqui você também encontrará muitos dos escritos da Dra. Catherine G. González, uma das pioneiras na educação teológica – algumas de autoria própria e outras em colaboração com Justo. Esses últimos recursos revelam claramente como os Drs. González têm colaborado e se apoiado ao longo dos anos.',
    'p3' => 'Ao longo de sua carreira de mais de sessenta anos, os Drs. González compartilharam seus pensamentos, análises e interpretações sobre uma ampla gama de temas que o inspirarão, informarão e desafiarão: ler a Bíblia de novas maneiras, encontrar o testemunho da igreja primitiva, reformar a educação teológica e praticar a justiça. Você encontrará tudo isso e muito mais ganhando vida aqui. Então, explore, faça pesquisas direcionadas, leia pequenos trechos dos documentos, aprenda com dois dos mais importantes líderes cristãos da atualidade e volte frequentemente, pois estamos constantemente carregando novos recursos.',
    'p4' => 'O acesso ao site está disponível apenas para aqueles que assinam o Centro de Recursos Justo e Catherine González ou são Amigos do Centro. Para adquirir uma assinatura, por favor <a href="https://aeth.info/en/afiliacion" target="_blank">clique aqui</a>. Para saber mais sobre como se tornar um Amigo do Centro e nos ajudar a garantir o acesso mundial ao trabalho do Dr. González, por favor <a href="friend.php" target="_blank">clique aqui</a>.',
    'p5' => 'Abaixo, no entanto, há dois exemplos de documentos disponíveis através de nossa coleção digital. Isso deve lhe dar uma ideia do que você poderia encontrar ao se tornar um Amigo do Centro ou assinante.',
    'p6' => 'Esta primeira peça, intitulada “Los ‘Padres’ Hispanos”, é uma de três palestras que Justo González deu em 2023 em um retiro de pastores hispânicos na Califórnia. Nela, ele explora a história do impacto dos “pais” espanhóis da igreja. Leia por si mesmo. <a href="https://gonzalezcenter.s3.us-east-2.amazonaws.com/d_hisp_01394.pdf" target="_blank"><i class="fas fa-file-pdf"></i> Baixar aqui</a>. A segunda peça é uma palestra intitulada “La Señal de Jonás”, que explora a diversidade da bondade e da criação de Deus. Embora o link disponível aqui seja para a versão em espanhol, este documento também está disponível em inglês e português. <a href="https://gonzalezcenter.s3.us-east-2.amazonaws.com/d_sena_00005.pdf" target="_blank"><i class="fas fa-file-pdf"></i> Baixar aqui</a>.',
),

);
